/**
 * Differential test: the TypeScript ETD port vs the Python runner.
 *
 * `server/vrm/etd/surgery.ts` and `vehicle-class.ts` are ports of
 * `etd-runner/scripts/book_cutover.py` and `vehicle_class.py`. Both originals earned
 * their quirks from real failures — a reservation booked in the wrong person's name, a
 * reservation booked at the template's branch behind correct-looking display strings, a
 * reservation booked in the template's class while the note promised another. A port
 * that is 99% right reproduces exactly those bugs, so "looks equivalent" is not a
 * standard worth anything here.
 *
 * The expectations are GENERATED by running the Python (see
 * tests/fixtures/etd-surgery/generate.py) rather than written by hand, so nobody's
 * reading of the Python is in the loop. Regenerate after any change to either side:
 *
 *     etd-runner/.venv/bin/python tests/fixtures/etd-surgery/generate.py
 *
 * The fixtures hold only the paths the surgery CHANGES plus their new (synthetic)
 * values — never the captured template's contents, which are real PII.
 *
 * No network, no database, no external system.
 */
import { test, describe } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

import {
  retarget,
  redate,
  relocate,
  setClass,
  setDriver,
  parseLocalDT,
  loadSavedrTemplate,
  templateOldIds,
  cloneTemplate,
  zipState,
  humanDT,
  fmtISO,
  addDaysDT,
} from "../server/vrm/etd/surgery";
import {
  choose,
  chooseSameVehicle,
  describeVehicle,
  descClass,
  descIsSedan,
  isHvac,
  preferredCodes,
  MODEL_MAP,
  SEDAN_LADDER,
  SIZE_ORDER,
  BODY_RANK,
  type OfferedClass,
} from "../server/vrm/etd/vehicle-class";

const FIX = path.join(process.cwd(), "tests", "fixtures", "etd-surgery");
const REMOVED = "__REMOVED__";

const readFixture = (name: string) => JSON.parse(fs.readFileSync(path.join(FIX, name), "utf-8"));

/** Every leaf as `a.b[0].c` -> value. Mirrors the generator's flatten() exactly. */
function flatten(node: unknown, prefix = "", out: Record<string, unknown> = {}): Record<string, unknown> {
  if (node && typeof node === "object" && !Array.isArray(node)) {
    const obj = node as Record<string, unknown>;
    const keys = Object.keys(obj);
    if (!keys.length) out[prefix] = {};
    for (const k of keys) flatten(obj[k], prefix ? `${prefix}.${k}` : k, out);
  } else if (Array.isArray(node)) {
    if (!node.length) out[prefix] = [];
    node.forEach((v, i) => flatten(v, `${prefix}[${i}]`, out));
  } else {
    out[prefix] = node;
  }
  return out;
}

function changedPaths(before: unknown, after: unknown): Record<string, unknown> {
  const a = flatten(before);
  const b = flatten(after);
  const out: Record<string, unknown> = {};
  for (const k of [...new Set([...Object.keys(a), ...Object.keys(b)])].sort()) {
    if (!(k in b)) out[k] = REMOVED;
    else if (!(k in a) || JSON.stringify(a[k]) !== JSON.stringify(b[k])) out[k] = b[k];
  }
  return out;
}

describe("ETD payload surgery matches the Python runner", () => {
  const fixture = readFixture("surgery.json");
  const template = loadSavedrTemplate();

  for (const scenario of fixture.cases as any[]) {
    test(scenario.name, () => {
      const inp = scenario.input;
      const { oldJ, oldR } = templateOldIds(template);
      const model = cloneTemplate(template);

      retarget(
        model,
        inp.journeyId,
        inp.reference,
        oldJ,
        oldR,
        inp.start,
        inp.end,
        (template as any).startDateTime,
        (template as any).endDateTime,
      );
      redate(model, parseLocalDT(inp.start), parseLocalDT(inp.end));
      relocate(model, inp.branch, inp.place);
      setClass(model, inp.pick);
      model.boboId = inp.user.userId;
      model.isBOBOToggleEnabled = true;
      model.isBOBOBooking = true;
      setDriver(model, inp.user, inp.ldap, inp.techName, inp.truck);
      if (inp.notes) {
        model.notes = inp.notes;
        model.notesViewModel = { reservationNote: inp.notes };
      }
      if (inp.bookingReferences) model.bookingReferences = inp.bookingReferences;

      const got = changedPaths(template, model);
      const want = scenario.changed as Record<string, unknown>;

      // Report the two failure directions separately: a path the port forgot is a very
      // different bug from a path it invented, and a single deepEqual on 200 paths says
      // neither.
      const missing = Object.keys(want).filter((k) => !(k in got));
      const extra = Object.keys(got).filter((k) => !(k in want));
      assert.deepEqual(missing, [], `paths Python changes and the port does not: ${missing.join(", ")}`);
      assert.deepEqual(extra, [], `paths the port changes and Python does not: ${extra.join(", ")}`);

      for (const [p, wantVal] of Object.entries(want)) {
        assert.deepEqual(
          JSON.parse(JSON.stringify(got[p] ?? null)),
          JSON.parse(JSON.stringify(wantVal ?? null)),
          `value differs at ${p}`,
        );
      }
    });
  }

  test("relocate refuses a branch that leaves the captured marker behind", () => {
    const guard = fixture.relocateGuard;
    const model = cloneTemplate(template);
    assert.throws(
      () => relocate(model, guard.branch, guard.place),
      (err: Error) => {
        // Same trigger AND the same named ghost — a port that throws for a different
        // reason has a different guard.
        assert.match(err.message, /still present after relocating/);
        const ghost = /captured branch marker (\S+)/.exec(guard.error)?.[1];
        assert.ok(ghost, "generator did not capture the ghost token");
        assert.ok(err.message.includes(ghost!), `expected the ${ghost} ghost, got: ${err.message}`);
        return true;
      },
    );
  });
});

describe("vehicle class selection matches the Python runner", () => {
  const fixture = readFixture("vehicle-class.json");

  test("the tables themselves are the same size and order", () => {
    assert.equal(Object.keys(MODEL_MAP).length, fixture.modelMapSize);
    assert.deepEqual(SEDAN_LADDER, fixture.sedanLadder);
    assert.deepEqual(SIZE_ORDER, fixture.sizeOrder);
    assert.deepEqual(BODY_RANK, fixture.bodyRank);
  });

  for (const c of fixture.cases as any[]) {
    test(c.name, () => {
      const [make, model, offered, a, b] = c.args;
      const got =
        c.fn === "choose"
          ? choose(make, model, offered as OfferedClass[], a, b)
          : chooseSameVehicle(make, model, offered as OfferedClass[], a);
      const want = c.expected;

      // `pick` is the offered-class object; compare by identity fields, not by
      // reference, since Python round-trips it through JSON.
      assert.equal(got.code, want.code ?? null, "code");
      assert.equal(got.match, want.match ?? null, "match");
      assert.equal(got.note, want.note ?? null, "note");
      assert.equal(got.changes_vehicle, want.changes_vehicle ?? null, "changes_vehicle");
      assert.deepEqual(
        got.pick ? { code: got.pick.code, description: got.pick.description } : null,
        want.pick ? { code: want.pick.code, description: want.pick.description } : null,
        "pick",
      );
    });
  }

  test("helper functions agree", () => {
    const run: Record<string, (args: any[]) => unknown> = {
      describe: ([mk, md, yr]) => describeVehicle(mk, md, yr),
      desc_class: ([t]) => descClass(t),
      desc_is_sedan: ([t]) => descIsSedan(t),
      is_hvac: ([t]) => isHvac(t),
      preferred_codes: ([mk, md]) => preferredCodes(mk, md),
    };
    for (const [fn, rows] of Object.entries(fixture.helpers as Record<string, [any[], unknown][]>)) {
      for (const [args, want] of rows) {
        assert.deepEqual(run[fn](args), want, `${fn}(${JSON.stringify(args)})`);
      }
    }
  });
});

describe("date and zip helpers", () => {
  test("humanDT stays English regardless of the host locale", () => {
    // The captured model's display strings are English; a server running under a
    // different locale must not start writing "lundi" into a reservation.
    assert.equal(humanDT(parseLocalDT("2026-09-08T09:00:00")), humanDT(parseLocalDT("2026-09-08T09:00:00")));
    assert.match(humanDT(parseLocalDT("2026-09-08T09:00:00")), /^[A-Z][a-z]+day, [A-Z][a-z]+ \d{1,2}, 2026/);
  });

  test("addDaysDT crosses months and years without a timezone in sight", () => {
    assert.equal(fmtISO(addDaysDT(parseLocalDT("2026-12-29T07:30:00"), 7)), "2027-01-05T07:30:00");
    assert.equal(fmtISO(addDaysDT(parseLocalDT("2026-02-27T00:00:00"), 2)), "2026-03-01T00:00:00");
  });

  test("zipState maps a ZIP to its state", () => {
    assert.equal(zipState("44100"), "OH");
    assert.equal(zipState("23701"), "VA");
    assert.equal(zipState(""), "");
  });
});
