/**
 * Reservation payload surgery — LINE-FOR-LINE PORT of the proven functions in
 * etd-runner/scripts/book_cutover.py (retarget / redate / relocate /
 * set_class / set_driver, plus the zip→state guard).
 *
 * These functions turn the captured savedr template
 * (etd-runner/reference/savedr_request.json — a REAL browser booking for a
 * prior driver) into a reservation for a different technician, branch, date
 * and vehicle class. Every one of them exists because of a real mis-booking:
 *
 *   - set_driver: reservation JAS57HG8OU booked in the captured driver's name
 *   - relocate:   JA70BDZ1M8 showed the right city, booked to Portsmouth 2102
 *   - set_class:  every booking reserved CFAR KONA until isSelected was found
 *   - redate:     /validate answers {"239": ["PICKUP DATE IS IN THE PAST"]}
 *
 * The ghost checks THROW rather than warn. A thrown ghost means the template
 * has fields this code does not know about; refusing to book is the point.
 * The differential test (tests/etd-surgery-differential.test.ts) pins this
 * port byte-for-byte to fixtures generated by the Python original.
 *
 * PII NOTE: the captured template carries the prior driver's contact details;
 * set_driver scrubs them unconditionally. Never log or persist the full model
 * from server code — evidence rows carry hashes and confirmation numbers only.
 */
import fs from "fs";
import path from "path";

// ---------------------------------------------------------------------------
// zip → state (wrong-geocode guard)
// ---------------------------------------------------------------------------

const ZIP_STATE: Array<[number, number, string]> = [
  [500, 528, "IA"], [600, 629, "IL"], [630, 658, "MO"], [660, 679, "KS"],
  [680, 693, "NE"], [700, 714, "LA"], [716, 729, "AR"], [730, 749, "OK"],
  [750, 799, "TX"], [800, 816, "CO"], [820, 831, "WY"], [832, 838, "ID"],
  [840, 847, "UT"], [850, 865, "AZ"], [870, 884, "NM"], [889, 898, "NV"],
  [900, 961, "CA"], [967, 968, "HI"], [970, 979, "OR"], [980, 994, "WA"],
  [995, 999, "AK"], [10, 27, "MA"], [28, 29, "RI"], [30, 38, "NH"],
  [39, 49, "ME"], [50, 59, "VT"], [60, 69, "CT"], [70, 89, "NJ"],
  [100, 149, "NY"], [150, 196, "PA"], [197, 199, "DE"], [200, 205, "DC"],
  [206, 219, "MD"], [220, 246, "VA"], [247, 268, "WV"], [270, 289, "NC"],
  [290, 299, "SC"], [300, 319, "GA"], [320, 349, "FL"], [350, 369, "AL"],
  [370, 385, "TN"], [386, 397, "MS"], [398, 399, "GA"], [400, 427, "KY"],
  [430, 459, "OH"], [460, 479, "IN"], [480, 499, "MI"], [530, 549, "WI"],
  [550, 567, "MN"], [570, 577, "SD"], [580, 588, "ND"], [590, 599, "MT"],
];

/** State from a zip's first three digits. Coarse but exactly the right tool:
 *  this only needs to catch a Niagara Falls masquerading as Ventura. */
export function zipState(zip5: unknown): string {
  const p = parseInt(String(zip5 ?? "").slice(0, 3), 10);
  if (!Number.isFinite(p)) return "";
  for (const [lo, hi, st] of ZIP_STATE) {
    if (lo <= p && p <= hi) return st;
  }
  return "";
}

// ---------------------------------------------------------------------------
// Naive local datetimes. The Python original uses timezone-naive datetime
// throughout ("2026-08-19T09:00:00"); JS Date would drag the process TZ into
// formatting, so this works on plain components instead.
// ---------------------------------------------------------------------------

export type SimpleDT = { y: number; mo: number; d: number; h: number; mi: number; s: number };

export function parseLocalDT(iso: string): SimpleDT {
  const m = /^(\d{4})-(\d{2})-(\d{2})[T ](\d{2}):(\d{2})(?::(\d{2}))?/.exec(String(iso).slice(0, 19));
  if (!m) throw new Error(`unparseable local datetime: ${String(iso).slice(0, 32)}`);
  return { y: +m[1], mo: +m[2], d: +m[3], h: +m[4], mi: +m[5], s: +(m[6] ?? "0") };
}

export function addDaysDT(dt: SimpleDT, days: number): SimpleDT {
  const t = new Date(Date.UTC(dt.y, dt.mo - 1, dt.d + days, dt.h, dt.mi, dt.s));
  return { y: t.getUTCFullYear(), mo: t.getUTCMonth() + 1, d: t.getUTCDate(), h: t.getUTCHours(), mi: t.getUTCMinutes(), s: t.getUTCSeconds() };
}

const pad2 = (n: number) => String(n).padStart(2, "0");
export const fmtISO = (dt: SimpleDT) => `${dt.y}-${pad2(dt.mo)}-${pad2(dt.d)}T${pad2(dt.h)}:${pad2(dt.mi)}:${pad2(dt.s)}`;
const fmtDate = (dt: SimpleDT) => `${dt.y}-${pad2(dt.mo)}-${pad2(dt.d)}`;
const fmtTime = (dt: SimpleDT) => `${pad2(dt.h)}:${pad2(dt.mi)}:${pad2(dt.s)}`;

const WEEKDAYS = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
const MONTHS = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];

/** Their display format: 'Tuesday, August 11, 2026 12:00:00 PM'. */
export function humanDT(dt: SimpleDT): string {
  const wd = WEEKDAYS[new Date(Date.UTC(dt.y, dt.mo - 1, dt.d)).getUTCDay()];
  const h12 = dt.h % 12 || 12;
  const ap = dt.h < 12 ? "AM" : "PM";
  return `${wd}, ${MONTHS[dt.mo - 1]} ${dt.d}, ${dt.y} ${h12}:${pad2(dt.mi)}:${pad2(dt.s)} ${ap}`;
}

// ---------------------------------------------------------------------------
// retarget — point the captured model at a fresh journey and these dates
// ---------------------------------------------------------------------------

export function retarget(
  node: unknown,
  journeyId: string,
  reference: string,
  oldJ: string | null | undefined,
  oldR: string | null | undefined,
  start: string,
  end: string,
  oldStart: string | null | undefined,
  oldEnd: string | null | undefined,
): void {
  if (node && typeof node === "object" && !Array.isArray(node)) {
    const obj = node as Record<string, unknown>;
    for (const k of Object.keys(obj)) {
      const v = obj[k];
      if (typeof v === "string") {
        if (v === oldJ) obj[k] = journeyId;
        else if (oldR && v === oldR) obj[k] = reference;
        else if (oldStart && v.startsWith(String(oldStart).slice(0, 16))) obj[k] = start;
        else if (oldEnd && v.startsWith(String(oldEnd).slice(0, 16))) obj[k] = end;
      } else {
        retarget(v, journeyId, reference, oldJ, oldR, start, end, oldStart, oldEnd);
      }
    }
  } else if (Array.isArray(node)) {
    for (const v of node) retarget(v, journeyId, reference, oldJ, oldR, start, end, oldStart, oldEnd);
  }
}

// ---------------------------------------------------------------------------
// redate — move every date in the captured model, in all four formats
// ---------------------------------------------------------------------------

/**
 * `retarget` only rewrites strings beginning with the captured ISO timestamp.
 * The other date-bearing fields keep the capture date in a format it does not
 * match: bare `2026-08-11`, bare `12:00:00`, the long display strings, and
 * `earliestPossibleEndDate`. Replacing by VALUE rather than by field path
 * means a field nobody has enumerated yet still gets moved.
 */
export function redate(model: Record<string, unknown>, start: SimpleDT, end: SimpleDT): number {
  const dtv = (model.dateTime ?? {}) as Record<string, unknown>;
  const oldS = dtv.startDateTime ?? (model as any).startDateTime;
  const oldE = dtv.endDateTime ?? (model as any).endDateTime;
  if (!(oldS && oldE)) return 0;
  const osDt = parseLocalDT(String(oldS));
  const oeDt = parseLocalDT(String(oldE));

  const sub = new Map<string, string>([
    [String(oldS), fmtISO(start)],
    [String(oldE), fmtISO(end)],
    [fmtDate(osDt), fmtDate(start)],
    [fmtDate(oeDt), fmtDate(end)],
    [fmtTime(osDt), fmtTime(start)],
    [fmtTime(oeDt), fmtTime(end)],
    [humanDT(osDt), humanDT(start)],
    [humanDT(oeDt), humanDT(end)],
  ]);
  // earliestPossibleEndDate carries a fractional second and an offset, so it
  // never equals any of the above. Match it on its date prefix instead.
  const earlyPrefix = fmtDate(osDt);

  let n = 0;
  const walk = (node: unknown): void => {
    if (node && typeof node === "object" && !Array.isArray(node)) {
      const obj = node as Record<string, unknown>;
      for (const k of Object.keys(obj)) {
        const v = obj[k];
        if (typeof v === "string") {
          if (sub.has(v)) {
            obj[k] = sub.get(v)!;
            n += 1;
          } else if (v.startsWith(earlyPrefix) && (v.includes("T") || v.includes(","))) {
            obj[k] = v.includes("T") ? `${fmtISO(start)}.0000000+00:00` : humanDT(start);
            n += 1;
          }
        } else {
          walk(v);
        }
      }
    } else if (Array.isArray(node)) {
      for (const v of node) walk(v);
    }
  };
  walk(model);
  return n;
}

// ---------------------------------------------------------------------------
// set_driver — replace EVERY trace of the captured driver
// ---------------------------------------------------------------------------

const escapeRe = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

export function setDriver(
  model: Record<string, unknown>,
  user: Record<string, unknown>,
  ldap: string,
  techName: string | null | undefined,
  truck: string,
): string[] {
  const changed: string[] = [];

  let first = String(user.firstName ?? "").trim();
  let last = String(user.lastName ?? "").trim();
  if (!(first && last)) {
    // Fall back to the survey name. "SCOTT,CORNELIUS" is surname-first;
    // "ALONSO CHAVIRA" is not.
    const nm = String(techName ?? "").trim();
    if (nm.includes(",")) {
      const i = nm.indexOf(",");
      last = nm.slice(0, i);
      first = nm.slice(i + 1);
    } else {
      const parts = nm.split(/\s+/).filter(Boolean);
      if (parts.length > 1) {
        first = parts[0];
        last = parts.slice(1).join(" ");
      } else {
        first = nm;
        last = "";
      }
    }
    first = first.trim();
    last = last.trim();
  }
  if (!(first && last)) throw new Error(`cannot resolve a driver name for ${ldap}`);

  const email = String((user.emailAddress ?? user.email ?? "") as string).trim();
  let phone = String((user.mobileNumber ?? (user as any).phone ?? (user as any).contactNumber ?? "") as string).replace(/\D/g, "");
  if (!phone && email.includes("@tmomail.net")) {
    // Provisioning made every address <10-digit-phone>@tmomail.net, so the
    // local part IS the phone when the profile carries none elsewhere.
    const local = email.split("@", 1)[0] ?? email.slice(0, email.indexOf("@"));
    if (/^\d{10}$/.test(local)) phone = local;
  }
  const bobo = String(user.userId ?? "");

  for (const blk of ["driverViewModel", "driverViewModelForBOBO"]) {
    const d = model[blk];
    if (!d || typeof d !== "object" || Array.isArray(d)) continue;
    const dd = d as Record<string, unknown>;
    dd.firstName = first;
    dd.lastName = last;
    changed.push(`${blk}.firstName`, `${blk}.lastName`);
    if (email) {
      dd.emailAddress = email;
      changed.push(`${blk}.emailAddress`);
    }
    if (bobo) {
      dd.boboId = bobo;
      changed.push(`${blk}.boboId`);
    }
    if (phone) {
      const cp = dd.contactPhoneNumber;
      if (cp && typeof cp === "object" && !Array.isArray(cp)) {
        (cp as Record<string, unknown>).number = phone;
        (cp as Record<string, unknown>).selectedInternationalDiallingCode = "1";
        changed.push(`${blk}.contactPhoneNumber.number`);
      }
      // The captured string says (+44) against a US number. Write the
      // country code we actually set rather than preserving that.
      dd.contactPhoneNumberString = `(+1)${phone}`;
      changed.push(`${blk}.contactPhoneNumberString`);
    }
  }

  if ("driverName" in model) {
    model.driverName = `${first} ${last}`.toUpperCase();
    changed.push("driverName");
  }
  if (email && "driverEmail" in model) {
    model.driverEmail = email;
    changed.push("driverEmail");
  }

  // The fields ETD actually stores and shows the branch. `bookingReferences`
  // is NOT this.
  const fields = ((model.additionalInformation as Record<string, unknown>)?.additionalInformationFields ?? []) as unknown[];
  for (const fld of Array.isArray(fields) ? fields : []) {
    if (!fld || typeof fld !== "object" || Array.isArray(fld)) continue;
    const f = fld as Record<string, unknown>;
    const name = String(f.fieldName ?? "").trim().toUpperCase();
    if (name.startsWith("TRUCK")) {
      f.fieldValue = String(truck);
      changed.push("additionalInformation.TruckNumber");
    } else if (name.startsWith("LDAP")) {
      f.fieldValue = ldap;
      changed.push("additionalInformation.LDAP");
    }
  }

  // Belt and braces: replace the captured driver's values ANYWHERE they
  // remain, by value. The targeted rewrites above cover the fields we know;
  // this sweep covers the ones we don't (the category that produced JAS57HG8OU).
  const sub = new Map<string, string>([
    ["MARK", first.toUpperCase()], ["Mark", first], ["mark", first.toLowerCase()],
    ["RAY", last.toUpperCase()], ["Ray", last], ["ray", last.toLowerCase()],
    ["MARK RAY", `${first} ${last}`.toUpperCase()],
    ["MRAY0", ldap],
    ["37046", String(truck)],
    // The captured driver's phone is scrubbed UNCONDITIONALLY. Leaving it
    // because we happen not to know the replacement still texts him about
    // someone else's rental.
    ["7577522030@tmomail.net", email || ""],
    ["7577522030", phone || ""],
    ["(+44)7577522030", phone ? `(+1)${phone}` : ""],
    ["(+1)7577522030", phone ? `(+1)${phone}` : ""],
  ]);

  const sweep = (node: unknown): void => {
    if (node && typeof node === "object" && !Array.isArray(node)) {
      const obj = node as Record<string, unknown>;
      for (const k of Object.keys(obj)) {
        const v = obj[k];
        if (typeof v === "string") {
          if (sub.has(v)) {
            obj[k] = sub.get(v)!;
            changed.push(`sweep:${k}`);
          } else if (v.includes("7577522030")) {
            obj[k] = v.split("7577522030").join(phone || "");
            changed.push(`sweep:${k}`);
          } else if (v.includes("MRAY0")) {
            obj[k] = v.split("MRAY0").join(ldap);
            changed.push(`sweep:${k}`);
          }
        } else {
          sweep(v);
        }
      }
    } else if (Array.isArray(node)) {
      // Strings sitting directly in a list (bookingReferences is one)
      // must be rewritten in place, not just recursed past.
      for (let i = 0; i < node.length; i++) {
        const v = node[i];
        if (typeof v === "string") {
          if (sub.has(v)) {
            node[i] = sub.get(v)!;
            changed.push("sweep:list");
          } else if (v.includes("MRAY0")) {
            node[i] = v.split("MRAY0").join(ldap).split("37046").join(String(truck));
            changed.push("sweep:list");
          } else if (v.includes("37046")) {
            node[i] = v.split("37046").join(String(truck));
            changed.push("sweep:list");
          }
        } else {
          sweep(v);
        }
      }
    }
  };
  sweep(model);

  // Fail loudly if the captured driver survived anywhere. Checked as whole
  // tokens, not substrings: a bare "MARK" also matches "MARKET ST", which is
  // a real Enterprise branch address and produced a false alarm on ACOVAS.
  const mine = `${first} ${last} ${ldap} ${truck} ${email}`.toUpperCase();
  const blob = JSON.stringify(model).toUpperCase();
  const ghosts = ["MARK RAY", "MRAY0", "7577522030"];
  if (String(truck) !== "37046") ghosts.push("37046"); // the captured driver's truck number
  for (const ghost of ghosts) {
    if (mine.includes(ghost)) continue;
    if (new RegExp(`(?<![A-Z0-9])${escapeRe(ghost)}(?![A-Z0-9])`).test(blob)) {
      throw new Error(
        `captured driver '${ghost}' still present after retargeting ${ldap}; ` +
          "refusing to book. The template has fields this function does not know about.",
      );
    }
  }

  // The driver blocks specifically must now name this technician.
  for (const blk of ["driverViewModel", "driverViewModelForBOBO"]) {
    const d = (model[blk] ?? {}) as Record<string, unknown>;
    if (
      String(d.firstName ?? "").toUpperCase() !== first.toUpperCase() ||
      String(d.lastName ?? "").toUpperCase() !== last.toUpperCase()
    ) {
      throw new Error(`${blk} did not take the new driver for ${ldap}`);
    }
  }
  return changed;
}

// ---------------------------------------------------------------------------
// set_class — write the CHOSEN vehicle class into the booking payload
// ---------------------------------------------------------------------------

/**
 * THE FIELD THAT ACTUALLY DECIDES: classInfo[*].brandInfo[*].isSelected.
 * The header fields (carClassCode etc.) are decorative; the buried flag is
 * the selection, stored as the strings 'True' / 'False'.
 */
/**
 * Swap the captured additional-info block for the account's current field list.
 *
 * The captured block is a snapshot of the account as it stood when the browser capture
 * was taken, and it goes stale silently: ETD answers a mismatch with one sentence,
 * `REQUIRED FIELD MISSING: ADDITIONALINFO`, naming no field. Values arrive empty from the
 * definition endpoint; `setDriver` fills them immediately after.
 */
export function useAccountAdditionalInfo(
  model: Record<string, unknown>,
  liveFields: unknown[],
): string[] {
  let block = model.additionalInformation as Record<string, unknown> | undefined;
  if (!block || typeof block !== "object" || Array.isArray(block)) {
    block = {};
    model.additionalInformation = block;
  }
  const fields: Record<string, unknown>[] = [];
  for (const src of Array.isArray(liveFields) ? liveFields : []) {
    if (!src || typeof src !== "object" || Array.isArray(src)) continue;
    const fld = JSON.parse(JSON.stringify(src)) as Record<string, unknown>;
    fld.fieldValue = fld.fieldValue ?? "";
    fld.fieldValueDateString = fld.fieldValueDateString ?? "";
    fields.push(fld);
  }
  block.additionalInformationFields = fields;
  return fields.map((f) => String(f.fieldName ?? "").trim());
}

/**
 * Drop any bookingReferences entry labelled Truck Number.
 *
 * Enterprise removed that field from the account, so the label refers to nothing. The
 * truck number belongs in the reservation's special notes and is put there by
 * renderRequestSpecialNotes / renderSpecialNotes. Deliberately narrow: the cutover's
 * `CLOSE Enterprise Ticket` and `Holman ARI Claim` entries are not account fields
 * either, and they are what ties a converted reservation back to its Holman ticket.
 */
export function stripTruckNumberReference(model: Record<string, unknown>): number {
  const refs = model.bookingReferences;
  if (!Array.isArray(refs)) return 0;
  const kept = refs.filter(
    (r) => !(typeof r === "string" && /^\s*(SHS\s+)?truck\s*number\b/i.test(r)),
  );
  const dropped = refs.length - kept.length;
  if (dropped) model.bookingReferences = kept;
  return dropped;
}

/**
 * Refuse to commit while a mandatory additional-info field is still empty.
 *
 * Fails closed and BY NAME. If Enterprise adds a field nothing here knows how to fill,
 * the alternative is ETD's generic refusal, which cost hours to attribute on 2026-08-17.
 */
export function assertAdditionalInfoComplete(model: Record<string, unknown>, ldap: string): void {
  const block = model.additionalInformation as Record<string, unknown> | undefined;
  const fields = (block?.additionalInformationFields ?? []) as unknown[];
  const missing: string[] = [];
  for (const fld of Array.isArray(fields) ? fields : []) {
    if (!fld || typeof fld !== "object" || Array.isArray(fld)) continue;
    const f = fld as Record<string, unknown>;
    if (f.mandatory && !String(f.fieldValue ?? "").trim()) {
      missing.push(String(f.fieldName ?? "?").trim());
    }
  }
  if (missing.length) {
    throw new Error(
      `account requires additional-info field(s) nothing fills: ${missing.join(", ")} ` +
        `(ldap ${ldap}). Teach setDriver the field, or have Enterprise confirm the ` +
        "account configuration.",
    );
  }
}

export function setClass(model: Record<string, unknown>, pick: Record<string, unknown>): void {
  const code = String(pick.code ?? "").toUpperCase();
  const desc = String(pick.description ?? "");
  if (!code) throw new Error("set_class called with no class code");
  const pax = String(pick.passengers ?? "5");
  const bags = String(pick.bags ?? "3");

  const cc = model.carClass;
  if (cc && typeof cc === "object" && !Array.isArray(cc)) {
    const ccd = cc as Record<string, unknown>;
    const oldId = String(ccd.carClassId ?? "");
    // Keep the captured id's tail fields (door counts etc.) and swap the
    // parts we actually know. Format observed:
    // CODE|DESC|True|False|passengers|bags||3|4|Unspecified
    const parts = oldId.split("|");
    if (parts.length >= 6) {
      parts[0] = code;
      parts[1] = desc;
      parts[4] = pax;
      parts[5] = bags;
      ccd.carClassId = parts.join("|");
    } else {
      ccd.carClassId = `${code}|${desc}|True|False|${pax}|${bags}||3|4|Unspecified`;
    }
    ccd.carClassCode = code;
    ccd.carClass = desc;
  }
  if ("vehicleClass" in model) {
    model.vehicleClass = `${code} - ${desc}`;
  }

  let flippedOn = 0;
  const info =
    cc && typeof cc === "object" && !Array.isArray(cc)
      ? ((cc as Record<string, unknown>).carsInformation as Record<string, unknown> | undefined)
      : undefined;
  const entries = ((info ?? {}).classInfo ?? []) as unknown[];
  for (const e of Array.isArray(entries) ? entries : []) {
    if (!e || typeof e !== "object" || Array.isArray(e)) continue;
    const ed = e as Record<string, unknown>;
    const isTarget = String(ed.modelCode ?? "").toUpperCase() === code;
    for (const b of (ed.brandInfo as unknown[]) ?? []) {
      if (b && typeof b === "object" && !Array.isArray(b) && "isSelected" in (b as Record<string, unknown>)) {
        (b as Record<string, unknown>).isSelected = isTarget ? "True" : "False";
        if (isTarget) flippedOn += 1;
      }
    }
  }
  if (flippedOn === 0) {
    throw new Error(
      `class ${code} is not in the template's classInfo list; the selection ` +
        "flag cannot be set, so ETD would book the captured class. Refusing.",
    );
  }

  // Verify both layers took.
  const got = String(((model.carClass ?? {}) as Record<string, unknown>).carClassCode ?? "").toUpperCase();
  if (got !== code) {
    throw new Error(`carClassCode is '${got}' after set_class(${code}); refusing to book`);
  }
  const liveSel: string[] = [];
  for (const e of Array.isArray(entries) ? entries : []) {
    if (!e || typeof e !== "object" || Array.isArray(e)) continue;
    const ed = e as Record<string, unknown>;
    for (const b of (ed.brandInfo as unknown[]) ?? []) {
      if (b && typeof b === "object" && !Array.isArray(b) && String((b as Record<string, unknown>).isSelected) === "True") {
        liveSel.push(String(ed.modelCode).toUpperCase());
      }
    }
  }
  if (!(liveSel.length === 1 && liveSel[0] === code)) {
    throw new Error(`isSelected flags wrong after set_class(${code}): ${JSON.stringify(liveSel)}`);
  }
}

// ---------------------------------------------------------------------------
// relocate — move the captured model to a different Enterprise branch
// ---------------------------------------------------------------------------

/**
 * The branch string format is theirs, taken verbatim from the capture:
 *   "Portsmouth Airline Blvd. (2102),2841 AIRLINE BLVD,PORTSMOUTH,23701-2704"
 *   = `${customerFacingBranchName} (${branchCode}),${fullAddress}`
 * The display fields are for humans; the `locations` block carries the
 * MACHINE identifiers (branchCode / stationId) that ETD actually books.
 */
export function relocate(
  model: Record<string, unknown>,
  branch: Record<string, unknown>,
  place: Record<string, unknown>,
): void {
  const name = String(branch.customerFacingBranchName ?? (branch as any).branchName ?? "");
  const code = String(branch.branchCode ?? "");
  const addr = String(branch.fullAddress ?? "");
  const branchStr = `${name} (${code}),${addr}`;
  const lat = String(branch.latitude ?? place.latitude ?? "");
  const lon = String(branch.longitude ?? place.longitude ?? "");
  const psid = String(branch.peoplesoftBranchId ?? "");
  const stid = String(branch.stationId ?? "");
  // The capture has no space after (+1); the branch record has one.
  const phone = String(branch.formattedPhoneNumber ?? "").replace(/\s+/g, "");

  for (const k of ["startLocationString", "endLocationString", "branchAddress", "startServicingBranch", "endServicingBranch"]) {
    if (k in model) model[k] = branchStr;
  }
  if ("branchTelephone" in model) model.branchTelephone = phone;
  if ("locationsURL" in model) model.locationsURL = `${lat}/${lon}/${lat}/${lon}`;

  for (const [k, v] of [
    ["startLatitude", lat], ["startLongitude", lon],
    ["endLatitude", lat], ["endLongitude", lon],
    ["startLocationPeopleSoftId", psid], ["startLocationStationId", stid],
    ["endLocationPeopleSoftId", psid], ["endLocationStationId", stid],
  ] as Array<[string, string]>) {
    if (k in model) model[k] = v;
  }

  const jvm = model.journeyViewModel;
  if (jvm && typeof jvm === "object" && !Array.isArray(jvm)) {
    const j = jvm as Record<string, unknown>;
    for (const key of ["startLocation", "endLocation"]) {
      const loc = j[key];
      if (loc && typeof loc === "object" && !Array.isArray(loc)) {
        const l = loc as Record<string, unknown>;
        l.location = (place.location as string) || addr;
        l.latitude = lat;
        l.longitude = lon;
        if ("peopleSoftId" in l) l.peopleSoftId = psid;
        if ("stationId" in l) l.stationId = stid;
      }
    }
    for (const [k, v] of [
      ["endPeopleSoftId", psid], ["endStationId", stid],
      ["endLatitude", lat], ["endLongitude", lon],
    ] as Array<[string, string]>) {
      if (k in j) j[k] = v;
    }
    // The waypoint list still pointed at the captured branch's address.
    for (const pt of (j.allPoints as unknown[]) ?? []) {
      if (pt && typeof pt === "object" && !Array.isArray(pt) && "destination" in (pt as Record<string, unknown>)) {
        (pt as Record<string, unknown>).destination = (place.location as string) || addr;
      }
    }
  }

  const nameUpper = name.toUpperCase();
  const desc = `${nameUpper}, ${addr}`.split(",,").join(",");
  const locs = model.locations;
  if (locs && typeof locs === "object" && !Array.isArray(locs)) {
    const ld = locs as Record<string, unknown>;
    for (const key of ["startLocation", "endLocation"]) {
      const loc = ld[key];
      if (!loc || typeof loc !== "object" || Array.isArray(loc)) continue;
      const l = loc as Record<string, unknown>;
      if ("branchDescription" in l) l.branchDescription = desc;
      if ("branchDescriptionWithBranchCode" in l) l.branchDescriptionWithBranchCode = branchStr;
      if ("branchCode" in l) l.branchCode = code;
      if ("stationId" in l) l.stationId = stid || l.stationId;
      if ("locationEditorName" in l) l.locationEditorName = nameUpper;
      for (const [k, v] of [
        ["latitude", lat], ["longitude", lon],
        ["peopleSoftId", psid], ["peoplesoftBranchId", psid],
      ] as Array<[string, string]>) {
        if (k in l) l[k] = v;
      }
    }
  }

  // Refuse to book if the captured branch survives anywhere. '2102' alone
  // is too short to grep safely, so check the two machine identifiers in
  // field positions plus the city name as a token.
  if (code !== "2102") {
    const blob = JSON.stringify(model).toUpperCase();
    for (const ghost of ['"E12102"', '"2102"', "PORTSMOUTH AIRLINE"]) {
      if (blob.includes(ghost)) {
        throw new Error(
          `captured branch marker ${ghost} still present after relocating to ` +
            `${code}; refusing to book. relocate() has a field it does not know about.`,
        );
      }
    }
  }
}

// ---------------------------------------------------------------------------
// Template + user-mapping loaders
// ---------------------------------------------------------------------------

const REF_DIR = path.resolve(process.cwd(), "etd-runner", "reference");
export const TEMPLATE_PATH = path.join(REF_DIR, "savedr_request.json");
export const MAPPING_PATH = path.join(REF_DIR, "etd_user_mapping.json");

let templateCache: Record<string, unknown> | null = null;
let mappingCache: Record<string, string> | null = null;

/** The captured savedr model. Throws when absent — it cannot be reconstructed. */
export function loadSavedrTemplate(): Record<string, unknown> {
  if (!templateCache) {
    if (!fs.existsSync(TEMPLATE_PATH)) {
      throw new Error(
        `Missing ${TEMPLATE_PATH}. It is the captured reservation model and cannot be reconstructed; re-capture it.`,
      );
    }
    templateCache = JSON.parse(fs.readFileSync(TEMPLATE_PATH, "utf-8"));
  }
  return templateCache!;
}

/** LDAP → ETD username (SHS- collision handles). Throws when absent. */
export function loadUserMapping(): Record<string, string> {
  if (!mappingCache) {
    if (!fs.existsSync(MAPPING_PATH)) {
      throw new Error(`${MAPPING_PATH} is missing. Run reconcile_roster.py or every SHS- collision case will fail to resolve.`);
    }
    mappingCache = JSON.parse(fs.readFileSync(MAPPING_PATH, "utf-8"));
  }
  return mappingCache!;
}

/** The template's own journey/reference ids, needed by retarget(). */
export function templateOldIds(template: Record<string, unknown>): { oldJ: string | null; oldR: string | null } {
  const jvm = (template.journeyViewModel ?? {}) as Record<string, unknown>;
  const oldJ = (template.journeyUId as string) || (jvm.journeyProfilerUId as string) || null;
  const oldR = (jvm.referenceNumber as string) || null;
  return { oldJ, oldR };
}

/** Deep copy for per-booking surgery; the cached template must stay pristine. */
export function cloneTemplate(template: Record<string, unknown>): Record<string, unknown> {
  return structuredClone(template);
}
