/**
 * Which vehicle class to reserve, and whether that is a change for the tech.
 *
 * LINE-FOR-LINE PORT of etd-runner/scripts/vehicle_class.py (the proven
 * booker's brain). The Python file remains the reference copy; the
 * differential test (tests/etd-vehicle-class-differential.test.ts) pins this
 * port to fixtures generated BY the Python original, so drift between the two
 * fails loudly instead of booking the wrong size of vehicle for a real person.
 *
 * Tyler's rule 2026-08-13, in two parts:
 *   1. If the technician is NOT HVAC, a SEDAN is reserved ("a full-size sedan
 *      or smaller with a lockable trunk").
 *   2. HVAC and refrigeration technicians keep a vehicle sized like the one
 *      they have. They carry equipment that does not fit in a trunk.
 *
 * ETD codes are SIPP/ACRISS. First letter size, second letter body:
 *   size  M mini · E economy · C compact · I intermediate · S standard
 *         F fullsize · P premium · L luxury
 *   body  C car · F SUV · G crossover · V van · P pickup · X special
 */

export type OfferedClass = {
  code?: string | null;
  description?: string | null;
  passengers?: unknown;
  bags?: unknown;
  [k: string]: unknown;
};

export type ClassChoice = {
  pick: OfferedClass | null;
  code: string;
  match: string;
  changes_vehicle: boolean | null;
  note: string;
};

// Holman model code -> ETD SIPP class, preferred first. Branch inventory
// differs, so more than one is listed where a sensible equivalent exists.
// Keys are `${MAKE}|${MODEL}` (Python used tuples).
export const MODEL_MAP: Record<string, string[]> = {
  // --- cars -------------------------------------------------------------
  "MITS|MIRA": ["ECAR", "CCAR"], // Mirage
  "NISN|VERS": ["CCAR", "ECAR"], // Versa
  "NISN|SENT": ["CCAR", "ICAR"], // Sentra
  "HOND|CIVC": ["CCAR", "ICAR"], // Civic
  "MAZD|3": ["ICAR", "CCAR"],
  "TOYO|CORO": ["ICAR", "SCAR"], // Corolla
  "TOYO|PRIU": ["ICAR", "SCAR"], // Prius
  "HYUN|ELAN": ["ICAR", "SCAR"], // Elantra
  "HYUN|ELAH": ["ICAR", "SCAR"],
  "KIA|K4": ["ICAR", "SCAR"],
  "VOLK|JETT": ["SCAR", "ICAR"], // Jetta
  "CHEV|MALI": ["FCAR", "SCAR"], // Malibu
  "NISN|ALTI": ["FCAR", "SCAR"], // Altima
  "TOYO|CAMR": ["FCAR", "SCAR"], // Camry
  "HOND|ACRD": ["FCAR", "SCAR"], // Accord
  "HYUN|SONA": ["FCAR", "SCAR"], // Sonata
  "HYUN|SONH": ["FCAR", "SCAR"],
  "KIA|K5": ["FCAR", "SCAR"],
  "GENE|G70": ["LCAR", "PCAR", "FCAR"],
  // --- compact / crossover SUV -----------------------------------------
  "CHEV|TRAX": ["CFAR", "IFAR"],
  "CHEV|TBLZ": ["CFAR", "IFAR"], // Trailblazer
  "MITS|OSPT": ["CFAR", "IFAR"], // Outlander Sport
  "MITS|ECLX": ["CFAR", "IFAR"], // Eclipse Cross
  "HYUN|KONA": ["CFAR", "IFAR"],
  "JEEP|COMP": ["CFAR", "IFAR"], // Compass
  "KIA|SOUL": ["CFAR", "IFAR"],
  "MAZD|CX30": ["CFAR", "IFAR"],
  "NISN|KICK": ["CFAR", "IFAR"],
  "VOLK|TAOS": ["CFAR", "IFAR"],
  "FORD|BSPT": ["CFAR", "IFAR"], // Bronco Sport
  "AUDI|Q3": ["CFAR", "IFAR"],
  "MERB|GLA": ["CFAR", "IFAR"],
  "MINI|CNTY": ["CFAR", "IFAR"],
  "BUIC|ENVS": ["CFAR", "IFAR"],
  // --- intermediate SUV -------------------------------------------------
  "NISN|ROGU": ["IFAR", "SFAR"], // Rogue
  "TOYO|RAV4": ["IFAR", "SFAR"],
  "HYUN|TUCS": ["IFAR", "SFAR"], // Tucson
  "MITS|OUTL": ["IFAR", "SFAR"], // Outlander
  "MAZD|CX5": ["IFAR", "SFAR"],
  "MAZD|CX50": ["IFAR", "SFAR"],
  "FORD|ESCA": ["IFAR", "SFAR"], // Escape
  // --- standard SUV -----------------------------------------------------
  "CHEV|EQUI": ["SFAR", "IFAR"], // Equinox
  "GMC|TERR": ["SFAR", "IFAR"], // Terrain
  "FORD|EDGE": ["SFAR", "IFAR"],
  "FORD|EXPL": ["SFAR", "FFAR"], // Explorer
  "HYUN|SANF": ["SFAR", "IFAR"], // Santa Fe
  "JEEP|GCHP": ["SFAR", "FFAR"], // Grand Cherokee
  "TOYO|HIGH": ["SFAR", "FFAR"], // Highlander
  "VOLK|ATLA": ["SFAR", "FFAR"], // Atlas
  "NISN|PATH": ["SGAR", "SFAR"], // Pathfinder
  "JEEP|WRAU": ["SFAR", "IFAR"], // Wrangler Unlimited
  "JEEP|WRUE": ["SFAR", "IFAR"],
  // --- fullsize / premium SUV ------------------------------------------
  "CHEV|TRAV": ["FFAR", "SFAR"], // Traverse
  "FORD|EXPE": ["FFAR", "PFAR"], // Expedition
  "GMC|YUKO": ["FFAR", "PFAR"], // Yukon
  "HYUN|PALI": ["FFAR", "SFAR"], // Palisade
  "MAZD|CX90": ["FFAR", "SFAR"],
  "DODG|DURA": ["PGAR", "FFAR"], // Durango
  "JEEP|WAGO": ["FFAR", "PFAR"], // Wagoneer
  "JEEP|WAGL": ["PFAR", "FFAR"], // Wagoneer L
  "JEEP|GWLN": ["PFAR", "FFAR"], // Grand Wagoneer L
  // --- minivans ---------------------------------------------------------
  "CHRY|PACI": ["MVAR"], // Pacifica
  "CHRY|PACH": ["MVAR"],
  "CHRY|VOYA": ["MVAR"], // Voyager
  "HOND|ODYS": ["MVAR"], // Odyssey
  "TOYO|SIEN": ["MVAR"], // Sienna
  // --- pickups ----------------------------------------------------------
  "NISN|FROC": ["SPAR", "PPAR"], // Frontier Crew
  "HOND|RIDG": ["SPAR", "PPAR"], // Ridgeline
  "JEEP|GLAD": ["SPBR", "SPAR"], // Gladiator
  "CHEV|S15C": ["PPAR", "PPBR"], // Silverado 1500
  "CHEV|S2HC": ["PPAR", "PPBR"], // Silverado 2500HD
  "FORD|F15C": ["PPAR", "PPBR"], // F-150
  "FORD|F25C": ["PPAR", "PPBR"], // F-250
  "GMC|K15C": ["PPAR", "PPBR"], // Sierra 1500
  "RAM|B15C": ["PPAR", "PPBR"], // Ram 1500
  "RAM|B25C": ["PPAR", "PPBR"], // Ram 2500
  // --- full-size vans ---------------------------------------------------
  "RAM|PM2H": ["RVAR", "FVAR"], // ProMaster 2500 high roof
  "FORD|T3MP": ["RVAR", "FVAR"], // Transit 350 passenger
  "MERB|S2HP": ["RVAR", "FVAR"], // Sprinter 2500 passenger
};

export const SIZE_ORDER = ["M", "E", "C", "I", "S", "F", "P", "L"];
export const BODY_RANK: Record<string, number> = { C: 0, X: 1, G: 2, F: 3, P: 4, V: 5 };

// The technician's own words, parsed. Model words first, generic body words
// as fallback; first match wins, so "Malibu" beats a stray "van" in
// "Malibu from the Vanderbilt branch".
const DESC_PATTERNS: Array<[string, string]> = [
  ["mirage", "ECAR"], ["versa", "CCAR"], ["sentra", "CCAR"],
  ["civic", "CCAR"], ["corolla", "ICAR"], ["prius", "ICAR"],
  ["elantra", "ICAR"], ["\\bk4\\b", "ICAR"], ["jetta", "SCAR"],
  ["malibu", "FCAR"], ["altima", "FCAR"], ["camry", "FCAR"],
  ["accord", "FCAR"], ["sonata", "FCAR"], ["\\bk5\\b", "FCAR"],
  ["impala", "FCAR"], ["fusion", "FCAR"], ["maxima", "PCAR"],
  ["charger", "FCAR"],
  ["pacifica", "MVAR"], ["voyager", "MVAR"], ["odyssey", "MVAR"],
  ["sienna", "MVAR"], ["carnival", "MVAR"], ["grand caravan", "MVAR"],
  ["mini? ?van", "MVAR"], // matches "minivan", "mini van", and the field's "min van"
  ["tacoma", "SPAR"], ["frontier", "SPAR"], ["gladiator", "SPBR"],
  ["ridgeline", "SPAR"], ["silverado", "PPAR"], ["\\bf.?150\\b", "PPAR"],
  ["\\bf.?250\\b", "PPAR"], ["sierra", "PPAR"], ["\\bram\\b", "PPAR"],
  ["tundra", "PPAR"], ["pick.?up|truck", "PPAR"],
  ["transit|promaster|sprinter|cargo van", "RVAR"],
  ["pathfinder", "SGAR"], ["durango", "PGAR"],
  ["tahoe|expedition|yukon|suburban", "FFAR"],
  ["wagoneer", "PFAR"], ["palisade|traverse|telluride|cx.?90|atlas", "FFAR"],
  ["highlander|explorer|grand cherokee|santa fe|pilot|4runner", "SFAR"],
  ["equinox|edge|terrain|murano|passport|blazer(?! ct)", "SFAR"],
  ["rogue|rav.?4|tucson|outlander(?! sport)|cx.?5|cx.?50|escape|forester|crv|cr-v|sportage", "IFAR"],
  ["kona|trax|trailblazer|eclipse cross|outlander sport|compass|soul|kicks?\\b|taos|bronco sport|hr-?v|crosstrek|venue|seltos|corsair|encore", "CFAR"],
  ["wrangler", "SFAR"],
  ["\\bsuv\\b|crossover", "IFAR"],
  ["sedan", "FCAR"],
];

/** SIPP class parsed from a human description, or '' if unrecognisable. */
export function descClass(text: string | null | undefined): string {
  const t = String(text ?? "").toLowerCase();
  if (!t.trim()) return "";
  for (const [pat, code] of DESC_PATTERNS) {
    if (new RegExp(pat).test(t)) return code;
  }
  return "";
}

/** true / false / null(unknown) — is the described vehicle a sedan? */
export function descIsSedan(text: string | null | undefined): boolean | null {
  const c = descClass(text);
  if (!c) return null;
  return SEDAN_CODES.has(c);
}

function rank(code: string): [number, number] {
  const c = String(code || "").toUpperCase();
  if (c.length < 2) return [99, 99];
  const body = BODY_RANK[c[1]] ?? 9;
  const size = SIZE_ORDER.includes(c[0]) ? SIZE_ORDER.indexOf(c[0]) : 50;
  return [body, size];
}

export function preferredCodes(make: string | null | undefined, model: string | null | undefined): string[] {
  const key = `${String(make ?? "").trim().toUpperCase()}|${String(model ?? "").trim().toUpperCase()}`;
  return [...(MODEL_MAP[key] ?? [])];
}

export function describeVehicle(
  make: string | null | undefined,
  model: string | null | undefined,
  year: string | null | undefined = null,
): string {
  const parts = [year ? String(year).trim() : "", String(make ?? "").trim(), String(model ?? "").trim()];
  return parts.filter((p) => p).join(" ");
}

// Sedans, smallest to largest, and walked in that order: take the smallest class
// the branch actually offers. FCAR is the ceiling, so PCAR and LCAR are deliberately
// excluded. Until 2026-08-17 this array was ordered largest-first, so the walk handed
// out a full-size to everyone whose branch had one, which is the opposite of
// right-sizing. `already_sedan` short-circuits before this, so a technician already in
// a sedan class the branch offers keeps that exact class rather than being moved down.
export const SEDAN_LADDER = ["ECAR", "CCAR", "ICAR", "SCAR", "FCAR"];
export const SEDAN_CODES = new Set(SEDAN_LADDER);

/**
 * Only when EVERY sedan rung is empty. Smallest first, so a full-size SUV or a
 * minivan is genuinely the last thing reached rather than a convenient default
 * (Tyler, 2026-08-18: "gated by what's available using the FSUV and larger only as
 * a last resort"). Before this the ladder simply stopped at FCAR and a branch with
 * no sedan produced REVIEW and no car, which is the worst outcome available: the
 * lot has vehicles and the technician goes home.
 */
export const ESCALATION_LADDER = ["CFAR", "IFAR", "SFAR", "FFAR", "MVAR"];

/**
 * Largest-first substitution ladder for a class Fleet NAMED that a branch does not
 * stock. The named-class walk goes DOWN from what was asked for; the plain sedan
 * default still walks UP from the smallest (SEDAN_LADDER). Stating the asymmetry
 * here because it is the whole rule: somebody who named a minivan needs space, and
 * somebody who said nothing gets the cheapest car that does the job.
 *
 * Mirrored verbatim by NAMED_DOWNGRADE in etd-runner/scripts/book_request.py. The two
 * bookers resolved the same request in OPPOSITE directions until 2026-08-19 - the
 * server took the largest class on the lot regardless of what was named, the runner
 * refused outright - so which vehicle a technician got depended on which program
 * happened to run. Change both or neither.
 *
 * Minivan is the ceiling (Tyler, 2026-08-17). Pickups are deliberately absent: an
 * open bed is not a substitute for enclosed space. PCAR and LCAR stay out for the
 * same reason they are out of SEDAN_LADDER - nobody promised them and they cost more.
 */
export const NAMED_DOWNGRADE = [...ESCALATION_LADDER].reverse()
  .concat([...SEDAN_LADDER].reverse());

/**
 * The classes Fleet may actually approve on a rental request, and the ETD class each
 * one means. This is the ONE list; the picker renders it and the API validates
 * against it, so the two cannot drift.
 *
 * It exists because `approved_vehicle_class` was free text up to 40 characters with
 * no validation anywhere. Whatever Fleet typed was stored verbatim and only failed
 * hours later, at booking, in front of a technician standing next to a dead van -
 * and "minivan" failed even when the branch had a minivan on the lot, because the
 * word was being compared against "CHRYSLER PACIFICA OR SIMILAR" as raw text.
 *
 * `sedan` maps to no single code on purpose: it means the sedan LADDER, walked
 * smallest-first, which is a different rule from naming a class outright.
 */
export const REQUEST_CLASS_OPTIONS: Array<{ label: string; sipp: string; note: string }> = [
  { label: "sedan", sipp: "", note: "Default. Smallest sedan the branch stocks, up to full-size." },
  { label: "suv", sipp: "IFAR", note: "Intermediate SUV (Nissan Rogue or similar)." },
  { label: "minivan", sipp: "MVAR", note: "Chrysler Pacifica or similar. The policy ceiling." },
  { label: "cargo van", sipp: "RVAR", note: "HVAC carve-out. Falls back to a minivan." },
  { label: "pickup truck", sipp: "PPAR", note: "Rarely stocked; falls back to the largest SUV." },
];

/**
 * The fixed dropdown the approval drawer renders: every class Enterprise
 * actually offers on its own reservation screen that policy allows Fleet to
 * name, plus the codeless sedan default. Fleet asked for SET choices — the
 * free-text/type-ahead picker made them delete "sedan" and guess what to
 * type. Values are exactly what `resolveRequestClass` accepts (the SIPP
 * codes in REQUEST_CLASS_CODES, or "sedan"), so the menu and the validator
 * cannot drift; descriptions mirror Enterprise's own "…or similar" wording.
 * PCAR/LCAR/premium codes stay out for the same policy reasons they are out
 * of the ladders above.
 */
export const ENTERPRISE_CLASS_MENU: Array<{ value: string; label: string; note: string }> = [
  { value: "sedan", label: "Sedan — smallest available (default)", note: "Walks the branch's sedans smallest-first, economy up to full-size." },
  { value: "ECAR", label: "Economy car (ECAR)", note: "Mitsubishi Mirage or similar." },
  { value: "CCAR", label: "Compact car (CCAR)", note: "Nissan Versa or similar." },
  { value: "ICAR", label: "Intermediate car (ICAR)", note: "Toyota Corolla or similar." },
  { value: "SCAR", label: "Standard car (SCAR)", note: "Volkswagen Jetta or similar." },
  { value: "FCAR", label: "Full-size car (FCAR)", note: "Nissan Altima or similar." },
  { value: "CFAR", label: "Compact SUV (CFAR)", note: "Hyundai Kona or similar." },
  { value: "IFAR", label: "Intermediate SUV (IFAR)", note: "Nissan Rogue or similar." },
  { value: "SFAR", label: "Standard SUV (SFAR)", note: "Chevrolet Equinox or similar." },
  { value: "FFAR", label: "Full-size SUV (FFAR)", note: "Nissan Pathfinder or similar." },
  { value: "MVAR", label: "Minivan (MVAR)", note: "Chrysler Pacifica or similar. The policy ceiling." },
  { value: "RVAR", label: "Cargo van (RVAR)", note: "Ford Transit or similar. HVAC carve-out; falls back to a minivan." },
  { value: "PPAR", label: "Pickup truck (PPAR)", note: "Ford F-150 or similar. Rarely stocked; falls back to the largest SUV." },
];

/** Every SIPP code a request may legitimately name, directly or via a label. */
export const REQUEST_CLASS_CODES = new Set<string>([
  ...SEDAN_LADDER, ...ESCALATION_LADDER, "RVAR", "PPAR",
]);

/**
 * Resolve what Fleet typed into a class this system can actually book.
 * Returns "" for the sedan default (deliberately codeless), or null when the text
 * means nothing to ETD - which is a 400, not a booking to discover later.
 */
export function resolveRequestClass(raw: string | null | undefined): string | null {
  const t = String(raw ?? "").trim().toLowerCase().replace(/[_-]+/g, " ").replace(/\s+/g, " ");
  if (!t) return null;
  if (t === "sedan") return "";
  if (/^[a-z]{4}$/.test(t)) {
    const up = t.toUpperCase();
    return REQUEST_CLASS_CODES.has(up) ? up : null;
  }
  const code = descClass(t);
  return code && REQUEST_CLASS_CODES.has(code) ? code : null;
}

const HVAC_PATTERN = /hvac|refrig|heat|air\s*cond/i;

export function isHvac(jobTitle: string | null | undefined): boolean {
  return HVAC_PATTERN.test(String(jobTitle ?? ""));
}

/**
 * Reserve a sedan, unless they are HVAC and need their current size.
 * Always reports whether this is a VEHICLE CHANGE for the technician.
 */
/**
 * Minivan is the ceiling (Tyler, 2026-08-17). The size-up walk must never climb past
 * MVAR into a full-size or passenger van: it is outside policy, and those classes are
 * not in the captured savedr template, so the booking refuses rather than upgrading.
 */
function aboveMinivan(r: [number, number]): boolean {
  const m = rank("MVAR");
  return r[0] === m[0] && r[1] > m[1];
}

export function choose(
  make: string | null | undefined,
  model: string | null | undefined,
  offered: OfferedClass[] | null | undefined,
  jobTitle: string | null | undefined = null,
  techDesc: string | null | undefined = null,
): ClassChoice {
  const byCode: Record<string, OfferedClass> = {};
  for (const c of offered ?? []) {
    const code = String(c?.code ?? "").toUpperCase();
    if (code && !(code in byCode)) byCode[code] = c;
  }
  if (Object.keys(byCode).length === 0) {
    return { pick: null, code: "", match: "NONE", changes_vehicle: null, note: "branch offered nothing" };
  }

  const current = preferredCodes(make, model);
  const currentCode = current.length ? current[0] : "";
  const hvac = isHvac(jobTitle);

  // ---------------------------------------------------------------- HVAC
  if (hvac) {
    if (!current.length) {
      return {
        pick: null, code: "", match: "UNMAPPED", changes_vehicle: null,
        // "None" rather than "null" is deliberate: this note is persisted evidence and
        // is shown to staff, and the Python runner (still the fallback) has always
        // written the Python spelling. An intent must read the same whichever runner
        // served it, so the port matches the text rather than improving it.
        // tests/etd-surgery-differential.test.ts pins them together.
        note:
          `HVAC tech and no make/model on the ticket ` +
          `(${make ?? "None"}/${model ?? "None"}); size cannot be inferred, needs a human`,
      };
    }
    for (const code of current) {
      if (code in byCode) {
        return {
          pick: byCode[code], code, match: "hvac_same_class", changes_vehicle: false,
          note: `HVAC: kept ${code} to match their ${describeVehicle(make, model)}`,
        };
      }
    }
    // Nearest size up in the same body style, never smaller.
    const target = rank(currentCode);
    const sameBody = Object.keys(byCode)
      .map((c) => [c, rank(c)] as [string, [number, number]])
      .filter((x) => x[1][0] === target[0])
      .filter((x) => !aboveMinivan(x[1]))
      .sort((a, b) => a[1][1] - b[1][1]);
    const up = sameBody.filter((x) => x[1][1] >= target[1]);
    if (up.length) {
      const code = up[0][0];
      return {
        pick: byCode[code], code, match: "hvac_nearest_up", changes_vehicle: true,
        note: `HVAC: ${currentCode} not offered, took ${code}`,
      };
    }
    return {
      pick: null, code: "", match: "HVAC_NO_MATCH", changes_vehicle: null,
      note: `HVAC needs ${currentCode}-equivalent; branch offers none. REVIEW`,
    };
  }

  // ------------------------------------------------------ everyone else
  // A sedan. TWO witnesses decide whether that is a CHANGE for them; the
  // tech's word wins in BOTH directions ("a Trax is not a sedan" ruling).
  const said = descClass(techDesc);
  const saidSedan: boolean | null = said ? SEDAN_CODES.has(said) : null;

  // Keep the exact class they already hold when either witness names a
  // sedan class that this branch offers.
  for (const held of [saidSedan ? said : "", SEDAN_CODES.has(currentCode) ? currentCode : ""]) {
    if (held && held in byCode) {
      return {
        pick: byCode[held], code: held, match: "already_sedan", changes_vehicle: false,
        note: `already in a sedan (${saidSedan && techDesc ? String(techDesc).trim() : describeVehicle(make, model)}); kept ${held}`,
      };
    }
  }

  for (const code of SEDAN_LADDER) {
    if (code in byCode) {
      let changed: boolean;
      if (saidSedan === true) changed = false; // their own words: already a sedan
      else if (saidSedan === false) changed = true; // their own words: SUV/van/truck
      else changed = !SEDAN_CODES.has(currentCode);
      return {
        pick: byCode[code],
        code,
        match: changed ? "rightsize_to_sedan" : "sedan",
        changes_vehicle: changed,
        note: changed
          ? `RIGHT-SIZE: currently ${String(techDesc ?? "").trim() || describeVehicle(make, model) || "unknown"}, reserving sedan ${code}`
          : `sedan ${code}`,
      };
    }
  }

  // Every sedan rung empty. Take the smallest thing the branch DOES have rather than
  // sending a stranded technician home, and say plainly that it is an escalation.
  for (const code of ESCALATION_LADDER) {
    if (code in byCode) {
      return {
        pick: byCode[code], code, match: "escalated_no_sedan", changes_vehicle: true,
        note: `no sedan at or below full-size offered; escalated to ${code} (smallest available above the sedan ceiling)`,
      };
    }
  }
  return {
    pick: null, code: "", match: "NO_VEHICLE", changes_vehicle: null,
    note: "branch offered nothing on the sedan ladder or the escalation ladder. REVIEW",
  };
}

// ------------------------------------------------------- ETD-description witness
// Byte-parallel port of the Python runner's `_etd_tokens` / `etd_class_for`
// (etd-runner/scripts/vehicle_class.py). Both runners share one differential
// fixture, so every string here must match Python's output exactly — including
// its repr() quoting.

const ETD_STOP = new Set(["OR", "SIMILAR", "AND", "SERIES", "GRAN", "COUPE", "AWD", "4WD", "WAGON"]);
const ETD_MAKES = new Set([
  "MITSUBISHI", "MITS", "NISSAN", "NISN", "TOYOTA", "TOYO", "VOLKSWAGEN", "VOLK",
  "CHRYSLER", "CHRY", "HYUNDAI", "HYUN", "CHEVROLET", "CHEV", "CHEVY", "MAZDA", "MAZD",
  "FORD", "JEEP", "DODGE", "DODG", "AUDI", "GENESIS", "BMW", "KIA", "HONDA", "HOND",
  "MERCEDES", "MERB", "MINI", "BUICK", "BUIC", "RAM", "GMC", "SUBARU", "LEXUS",
  "CADILLAC", "LINCOLN", "ACURA", "INFINITI", "VOLVO", "TESLA",
]);

/** Python's repr() for the strings that reach these notes. */
function pyRepr(s: string): string {
  if (s.includes("'") && !s.includes('"')) return `"${s}"`;
  return `'${s.replace(/\\/g, "\\\\").replace(/'/g, "\\'")}'`;
}

/** Distinctive tokens: not a make, not filler, not a model year. */
function etdTokens(text: unknown): string[] {
  const out: string[] = [];
  for (const w of String(text ?? "").toUpperCase().replace(/[^A-Z0-9 ]+/g, " ").split(/\s+/)) {
    if (!w) continue;
    if (ETD_STOP.has(w) || ETD_MAKES.has(w)) continue;
    if (/^\d{4}$/.test(w)) continue;
    if (w.length < 2) continue;
    out.push(w);
  }
  return out;
}

/** [code, why] read straight off ETD's class list. '' when it needs a human. */
function etdClassFor(vehicleText: string, offered: OfferedClass[] | null | undefined): [string, string] {
  const want = new Set(etdTokens(vehicleText));
  if (want.size === 0) return ["", `nothing identifiable in ${pyRepr(String(vehicleText ?? ""))}`];
  const hits = new Map<string, Set<string>>();
  for (const c of offered ?? []) {
    const code = String(c?.code ?? "").toUpperCase();
    if (!code) continue;
    // One description can name several exemplars, comma separated.
    for (const part of String(c?.description ?? "").split(",")) {
      for (const tok of etdTokens(part)) {
        if (want.has(tok)) {
          if (!hits.has(code)) hits.set(code, new Set());
          hits.get(code)!.add(tok);
        }
      }
    }
  }
  if (hits.size === 0) return ["", `no ETD class at this branch names ${pyRepr(vehicleText)}`];
  if (hits.size > 1) {
    const detail = [...hits.entries()]
      .sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0))
      .map(([k, v]) => `${k}(${[...v].sort().join("/")})`)
      .join(", ");
    return ["", `${pyRepr(vehicleText)} matches more than one ETD class (${detail}); needs a human`];
  }
  const code = hits.keys().next().value as string;
  return [code, `ETD lists ${[...hits.get(code)!].sort().join("/")} as ${code} at this branch`];
}

/**
 * Reserve the SAME vehicle they already have. No right-sizing, ever.
 * Cutover-intent rule: the workflow promises "NO VEHICLE CHANGE", so the
 * class must back that up. Unmapped feed = hard stop; size-up in the SAME
 * body style is the only permitted substitution.
 */
export function chooseSameVehicle(
  make: string | null | undefined,
  model: string | null | undefined,
  offered: OfferedClass[] | null | undefined,
  techDesc: string | null | undefined = null,
): ClassChoice {
  const byCode: Record<string, OfferedClass> = {};
  for (const c of offered ?? []) {
    const code = String(c?.code ?? "").toUpperCase();
    if (code && !(code in byCode)) byCode[code] = c;
  }
  if (Object.keys(byCode).length === 0) {
    return { pick: null, code: "", match: "NONE", changes_vehicle: null, note: "branch offered nothing" };
  }

  // ------------------------------------------------------------------ ETD first
  // Repair spec §9 said the FEED is the only witness that may pick a class, because
  // a vague "sedan" must not size a real reservation. That reasoning is right and is
  // preserved below — but it treated the hand-built MODEL_MAP as the only way to
  // read a vehicle, and that table not knowing a Corolla hard-stopped 30 of 37
  // bookings on 2026-08-19.
  //
  // ETD's own class list is a stronger witness than either: it is the branch's live
  // answer to exactly this question, and it cannot drift from what can be booked.
  // A single unambiguous MODEL match is accepted from the feed vehicle or, failing
  // that, from the technician's own words. Vague input still matches nothing and
  // still goes to a human, so §9's actual guarantee holds.
  const feedDesc = describeVehicle(make, model);
  let [etdCode, etdWhy] = etdClassFor(feedDesc, offered ?? []);
  let etdSrc = "feed";
  if (!etdCode && String(techDesc ?? "").trim()) {
    [etdCode, etdWhy] = etdClassFor(String(techDesc), offered ?? []);
    etdSrc = "technician";
  }

  const candidates = preferredCodes(make, model);

  // Where both witnesses speak and disagree, ETD wins — it is the one that decides
  // what actually gets booked — and the disagreement is reported so the table can be
  // corrected rather than quietly rotting.
  if (etdCode && candidates.length && candidates[0] !== etdCode && etdCode in byCode) {
    return {
      pick: byCode[etdCode], code: etdCode, match: "etd_description_over_table",
      changes_vehicle: false,
      note: `${etdWhy}; the local table said ${candidates[0]} - TABLE DRIFT, review MODEL_MAP for ${feedDesc || "this vehicle"}`,
    };
  }

  if (!candidates.length) {
    if (etdCode && etdCode in byCode) {
      return {
        pick: byCode[etdCode], code: etdCode, match: "etd_description", changes_vehicle: false,
        note: `${etdWhy} (read from the ${etdSrc}, no local mapping needed)`,
      };
    }
    const saidBit = String(techDesc ?? "").trim()
      ? ` / tech says ${pyRepr(String(techDesc).trim())}`
      : "";
    return {
      pick: null, code: "", match: "UNMAPPED", changes_vehicle: null,
      note: `no class mapping for ${feedDesc || "unknown vehicle"}${saidBit}; ${etdWhy}; same-vehicle booking needs a human`,
    };
  }

  // Exact PRIMARY class only — mapping alternates are not tried, because
  // some are smaller and "no vehicle change" must never quietly shrink
  // someone's vehicle.
  const primary = candidates[0];
  if (primary in byCode) {
    return {
      pick: byCode[primary], code: primary, match: "same_class", changes_vehicle: false,
      note: `kept ${primary} to match their ${describeVehicle(make, model) || "vehicle"}`,
    };
  }

  // Nearest size UP in the same body style; never smaller, never cross-body.
  const target = rank(primary);
  const sameBody = Object.keys(byCode)
    .map((c) => [c, rank(c)] as [string, [number, number]])
    .filter((x) => x[1][0] === target[0])
    .filter((x) => !aboveMinivan(x[1]))
    .sort((a, b) => a[1][1] - b[1][1]);
  const up = sameBody.filter((x) => x[1][1] >= target[1]);
  if (up.length) {
    const code = up[0][0];
    return {
      pick: byCode[code], code, match: "same_body_size_up", changes_vehicle: false,
      note: `${primary} not offered; took ${code} (same body, next size up)`,
    };
  }
  return {
    pick: null, code: "", match: "NO_MATCH", changes_vehicle: null,
    note: `branch offers no ${primary}-equivalent at or above their size. REVIEW`,
  };
}
