/**
 * Which vehicle class to reserve, and whether that is a change for the tech.
 *
 * LINE-FOR-LINE PORT of etd-runner/scripts/vehicle_class.py (the proven
 * booker's brain). The Python file remains the reference copy; the
 * differential test (tests/etd-vehicle-class-differential.test.ts) pins this
 * port to fixtures generated BY the Python original, so drift between the two
 * fails loudly instead of booking the wrong size of vehicle for a real person.
 *
 * Tyler's rule 2026-08-13, in two parts:
 *   1. If the technician is NOT HVAC, a SEDAN is reserved ("a full-size sedan
 *      or smaller with a lockable trunk").
 *   2. HVAC and refrigeration technicians keep a vehicle sized like the one
 *      they have. They carry equipment that does not fit in a trunk.
 *
 * ETD codes are SIPP/ACRISS. First letter size, second letter body:
 *   size  M mini · E economy · C compact · I intermediate · S standard
 *         F fullsize · P premium · L luxury
 *   body  C car · F SUV · G crossover · V van · P pickup · X special
 */

export type OfferedClass = {
  code?: string | null;
  description?: string | null;
  passengers?: unknown;
  bags?: unknown;
  [k: string]: unknown;
};

export type ClassChoice = {
  pick: OfferedClass | null;
  code: string;
  match: string;
  changes_vehicle: boolean | null;
  note: string;
};

// Holman model code -> ETD SIPP class, preferred first. Branch inventory
// differs, so more than one is listed where a sensible equivalent exists.
// Keys are `${MAKE}|${MODEL}` (Python used tuples).
export const MODEL_MAP: Record<string, string[]> = {
  // --- cars -------------------------------------------------------------
  "MITS|MIRA": ["ECAR", "CCAR"], // Mirage
  "NISN|VERS": ["CCAR", "ECAR"], // Versa
  "NISN|SENT": ["CCAR", "ICAR"], // Sentra
  "HOND|CIVC": ["CCAR", "ICAR"], // Civic
  "MAZD|3": ["ICAR", "CCAR"],
  "TOYO|CORO": ["ICAR", "SCAR"], // Corolla
  "TOYO|PRIU": ["ICAR", "SCAR"], // Prius
  "HYUN|ELAN": ["ICAR", "SCAR"], // Elantra
  "HYUN|ELAH": ["ICAR", "SCAR"],
  "KIA|K4": ["ICAR", "SCAR"],
  "VOLK|JETT": ["SCAR", "ICAR"], // Jetta
  "CHEV|MALI": ["FCAR", "SCAR"], // Malibu
  "NISN|ALTI": ["FCAR", "SCAR"], // Altima
  "TOYO|CAMR": ["FCAR", "SCAR"], // Camry
  "HOND|ACRD": ["FCAR", "SCAR"], // Accord
  "HYUN|SONA": ["FCAR", "SCAR"], // Sonata
  "HYUN|SONH": ["FCAR", "SCAR"],
  "KIA|K5": ["FCAR", "SCAR"],
  "GENE|G70": ["LCAR", "PCAR", "FCAR"],
  // --- compact / crossover SUV -----------------------------------------
  "CHEV|TRAX": ["CFAR", "IFAR"],
  "CHEV|TBLZ": ["CFAR", "IFAR"], // Trailblazer
  "MITS|OSPT": ["CFAR", "IFAR"], // Outlander Sport
  "MITS|ECLX": ["CFAR", "IFAR"], // Eclipse Cross
  "HYUN|KONA": ["CFAR", "IFAR"],
  "JEEP|COMP": ["CFAR", "IFAR"], // Compass
  "KIA|SOUL": ["CFAR", "IFAR"],
  "MAZD|CX30": ["CFAR", "IFAR"],
  "NISN|KICK": ["CFAR", "IFAR"],
  "VOLK|TAOS": ["CFAR", "IFAR"],
  "FORD|BSPT": ["CFAR", "IFAR"], // Bronco Sport
  "AUDI|Q3": ["CFAR", "IFAR"],
  "MERB|GLA": ["CFAR", "IFAR"],
  "MINI|CNTY": ["CFAR", "IFAR"],
  "BUIC|ENVS": ["CFAR", "IFAR"],
  // --- intermediate SUV -------------------------------------------------
  "NISN|ROGU": ["IFAR", "SFAR"], // Rogue
  "TOYO|RAV4": ["IFAR", "SFAR"],
  "HYUN|TUCS": ["IFAR", "SFAR"], // Tucson
  "MITS|OUTL": ["IFAR", "SFAR"], // Outlander
  "MAZD|CX5": ["IFAR", "SFAR"],
  "MAZD|CX50": ["IFAR", "SFAR"],
  "FORD|ESCA": ["IFAR", "SFAR"], // Escape
  // --- standard SUV -----------------------------------------------------
  "CHEV|EQUI": ["SFAR", "IFAR"], // Equinox
  "GMC|TERR": ["SFAR", "IFAR"], // Terrain
  "FORD|EDGE": ["SFAR", "IFAR"],
  "FORD|EXPL": ["SFAR", "FFAR"], // Explorer
  "HYUN|SANF": ["SFAR", "IFAR"], // Santa Fe
  "JEEP|GCHP": ["SFAR", "FFAR"], // Grand Cherokee
  "TOYO|HIGH": ["SFAR", "FFAR"], // Highlander
  "VOLK|ATLA": ["SFAR", "FFAR"], // Atlas
  "NISN|PATH": ["SGAR", "SFAR"], // Pathfinder
  "JEEP|WRAU": ["SFAR", "IFAR"], // Wrangler Unlimited
  "JEEP|WRUE": ["SFAR", "IFAR"],
  // --- fullsize / premium SUV ------------------------------------------
  "CHEV|TRAV": ["FFAR", "SFAR"], // Traverse
  "FORD|EXPE": ["FFAR", "PFAR"], // Expedition
  "GMC|YUKO": ["FFAR", "PFAR"], // Yukon
  "HYUN|PALI": ["FFAR", "SFAR"], // Palisade
  "MAZD|CX90": ["FFAR", "SFAR"],
  "DODG|DURA": ["PGAR", "FFAR"], // Durango
  "JEEP|WAGO": ["FFAR", "PFAR"], // Wagoneer
  "JEEP|WAGL": ["PFAR", "FFAR"], // Wagoneer L
  "JEEP|GWLN": ["PFAR", "FFAR"], // Grand Wagoneer L
  // --- minivans ---------------------------------------------------------
  "CHRY|PACI": ["MVAR"], // Pacifica
  "CHRY|PACH": ["MVAR"],
  "CHRY|VOYA": ["MVAR"], // Voyager
  "HOND|ODYS": ["MVAR"], // Odyssey
  "TOYO|SIEN": ["MVAR"], // Sienna
  // --- pickups ----------------------------------------------------------
  "NISN|FROC": ["SPAR", "PPAR"], // Frontier Crew
  "HOND|RIDG": ["SPAR", "PPAR"], // Ridgeline
  "JEEP|GLAD": ["SPBR", "SPAR"], // Gladiator
  "CHEV|S15C": ["PPAR", "PPBR"], // Silverado 1500
  "CHEV|S2HC": ["PPAR", "PPBR"], // Silverado 2500HD
  "FORD|F15C": ["PPAR", "PPBR"], // F-150
  "FORD|F25C": ["PPAR", "PPBR"], // F-250
  "GMC|K15C": ["PPAR", "PPBR"], // Sierra 1500
  "RAM|B15C": ["PPAR", "PPBR"], // Ram 1500
  "RAM|B25C": ["PPAR", "PPBR"], // Ram 2500
  // --- full-size vans ---------------------------------------------------
  "RAM|PM2H": ["RVAR", "FVAR"], // ProMaster 2500 high roof
  "FORD|T3MP": ["RVAR", "FVAR"], // Transit 350 passenger
  "MERB|S2HP": ["RVAR", "FVAR"], // Sprinter 2500 passenger
};

export const SIZE_ORDER = ["M", "E", "C", "I", "S", "F", "P", "L"];
export const BODY_RANK: Record<string, number> = { C: 0, X: 1, G: 2, F: 3, P: 4, V: 5 };

// The technician's own words, parsed. Model words first, generic body words
// as fallback; first match wins, so "Malibu" beats a stray "van" in
// "Malibu from the Vanderbilt branch".
const DESC_PATTERNS: Array<[string, string]> = [
  ["mirage", "ECAR"], ["versa", "CCAR"], ["sentra", "CCAR"],
  ["civic", "CCAR"], ["corolla", "ICAR"], ["prius", "ICAR"],
  ["elantra", "ICAR"], ["\\bk4\\b", "ICAR"], ["jetta", "SCAR"],
  ["malibu", "FCAR"], ["altima", "FCAR"], ["camry", "FCAR"],
  ["accord", "FCAR"], ["sonata", "FCAR"], ["\\bk5\\b", "FCAR"],
  ["impala", "FCAR"], ["fusion", "FCAR"], ["maxima", "PCAR"],
  ["charger", "FCAR"],
  ["pacifica", "MVAR"], ["voyager", "MVAR"], ["odyssey", "MVAR"],
  ["sienna", "MVAR"], ["carnival", "MVAR"], ["grand caravan", "MVAR"],
  ["mini? ?van", "MVAR"], // matches "minivan", "mini van", and the field's "min van"
  ["tacoma", "SPAR"], ["frontier", "SPAR"], ["gladiator", "SPBR"],
  ["ridgeline", "SPAR"], ["silverado", "PPAR"], ["\\bf.?150\\b", "PPAR"],
  ["\\bf.?250\\b", "PPAR"], ["sierra", "PPAR"], ["\\bram\\b", "PPAR"],
  ["tundra", "PPAR"], ["pick.?up|truck", "PPAR"],
  ["transit|promaster|sprinter|cargo van", "RVAR"],
  ["pathfinder", "SGAR"], ["durango", "PGAR"],
  ["tahoe|expedition|yukon|suburban", "FFAR"],
  ["wagoneer", "PFAR"], ["palisade|traverse|telluride|cx.?90|atlas", "FFAR"],
  ["highlander|explorer|grand cherokee|santa fe|pilot|4runner", "SFAR"],
  ["equinox|edge|terrain|murano|passport|blazer(?! ct)", "SFAR"],
  ["rogue|rav.?4|tucson|outlander(?! sport)|cx.?5|cx.?50|escape|forester|crv|cr-v|sportage", "IFAR"],
  ["kona|trax|trailblazer|eclipse cross|outlander sport|compass|soul|kicks?\\b|taos|bronco sport|hr-?v|crosstrek|venue|seltos|corsair|encore", "CFAR"],
  ["wrangler", "SFAR"],
  ["\\bsuv\\b|crossover", "IFAR"],
  ["sedan", "FCAR"],
];

/** SIPP class parsed from a human description, or '' if unrecognisable. */
export function descClass(text: string | null | undefined): string {
  const t = String(text ?? "").toLowerCase();
  if (!t.trim()) return "";
  for (const [pat, code] of DESC_PATTERNS) {
    if (new RegExp(pat).test(t)) return code;
  }
  return "";
}

/** true / false / null(unknown) — is the described vehicle a sedan? */
export function descIsSedan(text: string | null | undefined): boolean | null {
  const c = descClass(text);
  if (!c) return null;
  return SEDAN_CODES.has(c);
}

function rank(code: string): [number, number] {
  const c = String(code || "").toUpperCase();
  if (c.length < 2) return [99, 99];
  const body = BODY_RANK[c[1]] ?? 9;
  const size = SIZE_ORDER.includes(c[0]) ? SIZE_ORDER.indexOf(c[0]) : 50;
  return [body, size];
}

export function preferredCodes(make: string | null | undefined, model: string | null | undefined): string[] {
  const key = `${String(make ?? "").trim().toUpperCase()}|${String(model ?? "").trim().toUpperCase()}`;
  return [...(MODEL_MAP[key] ?? [])];
}

export function describeVehicle(
  make: string | null | undefined,
  model: string | null | undefined,
  year: string | null | undefined = null,
): string {
  const parts = [year ? String(year).trim() : "", String(make ?? "").trim(), String(model ?? "").trim()];
  return parts.filter((p) => p).join(" ");
}

// Sedans, smallest to largest. FCAR is the ceiling: the SOP promises a
// full-size sedan or smaller, so PCAR and LCAR are deliberately excluded.
export const SEDAN_LADDER = ["FCAR", "SCAR", "ICAR", "CCAR", "ECAR"];
export const SEDAN_CODES = new Set(SEDAN_LADDER);

const HVAC_PATTERN = /hvac|refrig|heat|air\s*cond/i;

export function isHvac(jobTitle: string | null | undefined): boolean {
  return HVAC_PATTERN.test(String(jobTitle ?? ""));
}

/**
 * Reserve a sedan, unless they are HVAC and need their current size.
 * Always reports whether this is a VEHICLE CHANGE for the technician.
 */
export function choose(
  make: string | null | undefined,
  model: string | null | undefined,
  offered: OfferedClass[] | null | undefined,
  jobTitle: string | null | undefined = null,
  techDesc: string | null | undefined = null,
): ClassChoice {
  const byCode: Record<string, OfferedClass> = {};
  for (const c of offered ?? []) {
    const code = String(c?.code ?? "").toUpperCase();
    if (code && !(code in byCode)) byCode[code] = c;
  }
  if (Object.keys(byCode).length === 0) {
    return { pick: null, code: "", match: "NONE", changes_vehicle: null, note: "branch offered nothing" };
  }

  const current = preferredCodes(make, model);
  const currentCode = current.length ? current[0] : "";
  const hvac = isHvac(jobTitle);

  // ---------------------------------------------------------------- HVAC
  if (hvac) {
    if (!current.length) {
      return {
        pick: null, code: "", match: "UNMAPPED", changes_vehicle: null,
        // "None" rather than "null" is deliberate: this note is persisted evidence and
        // is shown to staff, and the Python runner (still the fallback) has always
        // written the Python spelling. An intent must read the same whichever runner
        // served it, so the port matches the text rather than improving it.
        // tests/etd-surgery-differential.test.ts pins them together.
        note:
          `HVAC tech and no make/model on the ticket ` +
          `(${make ?? "None"}/${model ?? "None"}); size cannot be inferred, needs a human`,
      };
    }
    for (const code of current) {
      if (code in byCode) {
        return {
          pick: byCode[code], code, match: "hvac_same_class", changes_vehicle: false,
          note: `HVAC: kept ${code} to match their ${describeVehicle(make, model)}`,
        };
      }
    }
    // Nearest size up in the same body style, never smaller.
    const target = rank(currentCode);
    const sameBody = Object.keys(byCode)
      .map((c) => [c, rank(c)] as [string, [number, number]])
      .filter((x) => x[1][0] === target[0])
      .sort((a, b) => a[1][1] - b[1][1]);
    const up = sameBody.filter((x) => x[1][1] >= target[1]);
    if (up.length) {
      const code = up[0][0];
      return {
        pick: byCode[code], code, match: "hvac_nearest_up", changes_vehicle: true,
        note: `HVAC: ${currentCode} not offered, took ${code}`,
      };
    }
    return {
      pick: null, code: "", match: "HVAC_NO_MATCH", changes_vehicle: null,
      note: `HVAC needs ${currentCode}-equivalent; branch offers none. REVIEW`,
    };
  }

  // ------------------------------------------------------ everyone else
  // A sedan. TWO witnesses decide whether that is a CHANGE for them; the
  // tech's word wins in BOTH directions ("a Trax is not a sedan" ruling).
  const said = descClass(techDesc);
  const saidSedan: boolean | null = said ? SEDAN_CODES.has(said) : null;

  // Keep the exact class they already hold when either witness names a
  // sedan class that this branch offers.
  for (const held of [saidSedan ? said : "", SEDAN_CODES.has(currentCode) ? currentCode : ""]) {
    if (held && held in byCode) {
      return {
        pick: byCode[held], code: held, match: "already_sedan", changes_vehicle: false,
        note: `already in a sedan (${saidSedan && techDesc ? String(techDesc).trim() : describeVehicle(make, model)}); kept ${held}`,
      };
    }
  }

  for (const code of SEDAN_LADDER) {
    if (code in byCode) {
      let changed: boolean;
      if (saidSedan === true) changed = false; // their own words: already a sedan
      else if (saidSedan === false) changed = true; // their own words: SUV/van/truck
      else changed = !SEDAN_CODES.has(currentCode);
      return {
        pick: byCode[code],
        code,
        match: changed ? "rightsize_to_sedan" : "sedan",
        changes_vehicle: changed,
        note: changed
          ? `RIGHT-SIZE: currently ${String(techDesc ?? "").trim() || describeVehicle(make, model) || "unknown"}, reserving sedan ${code}`
          : `sedan ${code}`,
      };
    }
  }

  return {
    pick: null, code: "", match: "NO_SEDAN", changes_vehicle: null,
    note: "branch offered no sedan at or below full-size. REVIEW",
  };
}

/**
 * Reserve the SAME vehicle they already have. No right-sizing, ever.
 * Cutover-intent rule: the workflow promises "NO VEHICLE CHANGE", so the
 * class must back that up. Unmapped feed = hard stop; size-up in the SAME
 * body style is the only permitted substitution.
 */
export function chooseSameVehicle(
  make: string | null | undefined,
  model: string | null | undefined,
  offered: OfferedClass[] | null | undefined,
  techDesc: string | null | undefined = null,
): ClassChoice {
  const byCode: Record<string, OfferedClass> = {};
  for (const c of offered ?? []) {
    const code = String(c?.code ?? "").toUpperCase();
    if (code && !(code in byCode)) byCode[code] = c;
  }
  if (Object.keys(byCode).length === 0) {
    return { pick: null, code: "", match: "NONE", changes_vehicle: null, note: "branch offered nothing" };
  }

  // The FEED is the only witness that may pick a class (repair spec §9).
  const candidates = preferredCodes(make, model);
  if (!candidates.length) {
    const saidBit = String(techDesc ?? "").trim()
      ? ` / tech says '${String(techDesc).trim()}'`
      : "";
    return {
      pick: null, code: "", match: "UNMAPPED", changes_vehicle: null,
      note: `no class mapping for ${describeVehicle(make, model) || "unknown vehicle"}${saidBit}; same-vehicle booking needs a human`,
    };
  }

  // Exact PRIMARY class only — mapping alternates are not tried, because
  // some are smaller and "no vehicle change" must never quietly shrink
  // someone's vehicle.
  const primary = candidates[0];
  if (primary in byCode) {
    return {
      pick: byCode[primary], code: primary, match: "same_class", changes_vehicle: false,
      note: `kept ${primary} to match their ${describeVehicle(make, model) || "vehicle"}`,
    };
  }

  // Nearest size UP in the same body style; never smaller, never cross-body.
  const target = rank(primary);
  const sameBody = Object.keys(byCode)
    .map((c) => [c, rank(c)] as [string, [number, number]])
    .filter((x) => x[1][0] === target[0])
    .sort((a, b) => a[1][1] - b[1][1]);
  const up = sameBody.filter((x) => x[1][1] >= target[1]);
  if (up.length) {
    const code = up[0][0];
    return {
      pick: byCode[code], code, match: "same_body_size_up", changes_vehicle: false,
      note: `${primary} not offered; took ${code} (same body, next size up)`,
    };
  }
  return {
    pick: null, code: "", match: "NO_MATCH", changes_vehicle: null,
    note: `branch offers no ${primary}-equivalent at or above their size. REVIEW`,
  };
}
