import type { TechStatus, GateClassification, DCAOutcome } from "./constants";

export type OutreachStatus = "recent" | "overdue" | "no_contact" | "completed";

export interface DummyTech {
  id: string;
  name: string;
  ldap: string;
  market: string;
  currentStatus: TechStatus;
  daysInStatus: number;
  adjustedNet: number;
  gateClassification: GateClassification;
  lastOutreachAction: string;
  lastOutreachDate: string;
  nextAction: string;
  nextActionOverdue: boolean;
  nextActionDueToday: boolean;
  autoFlagged: boolean;
  tenureMonths: number;
  dcaName: string;
  teamLeadName: string;
  teamLeadPhone: string;
  gate2Exempt: boolean;
  newHireExempt: boolean;
  dcaReviewOutcome: DCAOutcome;
  rentalStartDate: string;
  outreachStatus: OutreachStatus;
}

export const dummyTechs: DummyTech[] = [
  {
    id: "a1b2c3d4",
    name: "Marcus Williams",
    ldap: "mwillia4",
    market: "Chicago",
    currentStatus: "in_rental",
    daysInStatus: 42,
    adjustedNet: -3280,
    gateClassification: "underwater",
    lastOutreachAction: "Text sent",
    lastOutreachDate: "Mar 28",
    nextAction: "Follow-up call",
    nextActionOverdue: true,
    nextActionDueToday: false,
    autoFlagged: true,
    tenureMonths: 18,
    dcaName: "David Chen",
    teamLeadName: "Angela Morris",
    teamLeadPhone: "(312) 555-0142",
    gate2Exempt: false,
    newHireExempt: false,
    dcaReviewOutcome: "cleared",
    rentalStartDate: "2025-09-15",
    outreachStatus: "overdue",
  },
  {
    id: "e5f6g7h8",
    name: "Jasmine Torres",
    ldap: "jtorre12",
    market: "Dallas",
    currentStatus: "exception_paired",
    daysInStatus: 28,
    adjustedNet: -1150,
    gateClassification: "underwater",
    lastOutreachAction: "Exception opened",
    lastOutreachDate: "Mar 18",
    nextAction: "21-day review",
    nextActionOverdue: false,
    nextActionDueToday: true,
    autoFlagged: false,
    tenureMonths: 14,
    dcaName: "Sarah Kim",
    teamLeadName: "Robert Diaz",
    teamLeadPhone: "(214) 555-0198",
    gate2Exempt: false,
    newHireExempt: false,
    dcaReviewOutcome: "cleared",
    rentalStartDate: "2025-11-01",
    outreachStatus: "recent",
  },
  {
    id: "i9j0k1l2",
    name: "DeAndre Jackson",
    ldap: "djacks07",
    market: "Atlanta",
    currentStatus: "escalated_carl",
    daysInStatus: 5,
    adjustedNet: -4510,
    gateClassification: "underwater",
    lastOutreachAction: "Escalated",
    lastOutreachDate: "Mar 26",
    nextAction: "Pending Carl's call",
    nextActionOverdue: false,
    nextActionDueToday: false,
    autoFlagged: true,
    tenureMonths: 22,
    dcaName: "Mike Patterson",
    teamLeadName: "Lisa Nguyen",
    teamLeadPhone: "(404) 555-0167",
    gate2Exempt: false,
    newHireExempt: false,
    dcaReviewOutcome: "cleared",
    rentalStartDate: "2025-05-20",
    outreachStatus: "overdue",
  },
  {
    id: "m3n4o5p6",
    name: "Christina Perez",
    ldap: "cperez09",
    market: "Miami",
    currentStatus: "byov_enrolled",
    daysInStatus: 12,
    adjustedNet: 2100,
    gateClassification: "marginal",
    lastOutreachAction: "BYOV enrolled",
    lastOutreachDate: "Mar 19",
    nextAction: "Closed",
    nextActionOverdue: false,
    nextActionDueToday: false,
    autoFlagged: false,
    tenureMonths: 31,
    dcaName: "James Wilson",
    teamLeadName: "Karen Stewart",
    teamLeadPhone: "(305) 555-0134",
    gate2Exempt: false,
    newHireExempt: false,
    dcaReviewOutcome: "cleared",
    rentalStartDate: "2024-08-10",
    outreachStatus: "completed",
  },
  {
    id: "q7r8s9t0",
    name: "Brian Murphy",
    ldap: "bmurph03",
    market: "Phoenix",
    currentStatus: "in_rental",
    daysInStatus: 67,
    adjustedNet: 1850,
    gateClassification: "marginal",
    lastOutreachAction: "Call completed",
    lastOutreachDate: "Mar 24",
    nextAction: "Send text",
    nextActionOverdue: false,
    nextActionDueToday: false,
    autoFlagged: false,
    tenureMonths: 26,
    dcaName: "Rachel Adams",
    teamLeadName: "Tom Bradley",
    teamLeadPhone: "(602) 555-0189",
    gate2Exempt: false,
    newHireExempt: false,
    dcaReviewOutcome: "pending",
    rentalStartDate: "2025-01-24",
    outreachStatus: "recent",
  },
  {
    id: "u1v2w3x4",
    name: "Keisha Brown",
    ldap: "kbrown21",
    market: "Houston",
    currentStatus: "exception_home_learning",
    daysInStatus: 34,
    adjustedNet: -890,
    gateClassification: "underwater",
    lastOutreachAction: "Exception opened",
    lastOutreachDate: "Feb 26",
    nextAction: "Log reachability",
    nextActionOverdue: true,
    nextActionDueToday: false,
    autoFlagged: true,
    tenureMonths: 19,
    dcaName: "Anthony Lewis",
    teamLeadName: "Maria Gonzalez",
    teamLeadPhone: "(713) 555-0156",
    gate2Exempt: false,
    newHireExempt: false,
    dcaReviewOutcome: "cleared",
    rentalStartDate: "2025-08-03",
    outreachStatus: "overdue",
  },
  {
    id: "y5z6a7b8",
    name: "Robert Chen",
    ldap: "rchen14",
    market: "Los Angeles",
    currentStatus: "in_rental",
    daysInStatus: 15,
    adjustedNet: 4200,
    gateClassification: "marginal",
    lastOutreachAction: "Text sent",
    lastOutreachDate: "Mar 30",
    nextAction: "Await response",
    nextActionOverdue: false,
    nextActionDueToday: false,
    autoFlagged: false,
    tenureMonths: 36,
    dcaName: "Patricia Moore",
    teamLeadName: "Steve Johnson",
    teamLeadPhone: "(213) 555-0178",
    gate2Exempt: false,
    newHireExempt: false,
    dcaReviewOutcome: "cleared",
    rentalStartDate: "2024-12-15",
    outreachStatus: "recent",
  },
  {
    id: "c9d0e1f2",
    name: "Tamika Davis",
    ldap: "tdavis18",
    market: "Detroit",
    currentStatus: "epv_issued",
    daysInStatus: 3,
    adjustedNet: -5640,
    gateClassification: "underwater",
    lastOutreachAction: "EPV confirmed",
    lastOutreachDate: "Mar 29",
    nextAction: "Rental stop Mar 31",
    nextActionOverdue: false,
    nextActionDueToday: false,
    autoFlagged: false,
    tenureMonths: 12,
    dcaName: "Kevin Thompson",
    teamLeadName: "Diana Hall",
    teamLeadPhone: "(313) 555-0145",
    gate2Exempt: false,
    newHireExempt: false,
    dcaReviewOutcome: "cleared",
    rentalStartDate: "2025-03-20",
    outreachStatus: "completed",
  },
  {
    id: "g3h4i5j6",
    name: "Samuel Okafor",
    ldap: "sokafo06",
    market: "Minneapolis",
    currentStatus: "in_rental",
    daysInStatus: 51,
    adjustedNet: -2340,
    gateClassification: "underwater",
    lastOutreachAction: "Text sent",
    lastOutreachDate: "Mar 22",
    nextAction: "Follow-up call",
    nextActionOverdue: false,
    nextActionDueToday: true,
    autoFlagged: false,
    tenureMonths: 15,
    dcaName: "Emily Watson",
    teamLeadName: "Chris Taylor",
    teamLeadPhone: "(612) 555-0123",
    gate2Exempt: false,
    newHireExempt: false,
    dcaReviewOutcome: "pending",
    rentalStartDate: "2025-02-08",
    outreachStatus: "recent",
  },
  {
    id: "k7l8m9n0",
    name: "Angela Martinez",
    ldap: "amarti22",
    market: "Denver",
    currentStatus: "resolved",
    daysInStatus: 8,
    adjustedNet: -1780,
    gateClassification: "underwater",
    lastOutreachAction: "BYOV enrolled",
    lastOutreachDate: "Mar 23",
    nextAction: "None",
    nextActionOverdue: false,
    nextActionDueToday: false,
    autoFlagged: false,
    tenureMonths: 28,
    dcaName: "Brian Foster",
    teamLeadName: "Nicole Ramirez",
    teamLeadPhone: "(720) 555-0167",
    gate2Exempt: false,
    newHireExempt: false,
    dcaReviewOutcome: "cleared",
    rentalStartDate: "2024-04-12",
    outreachStatus: "completed",
  },
  {
    id: "o1p2q3r4",
    name: "Darius Thompson",
    ldap: "dthom11",
    market: "Seattle",
    currentStatus: "in_rental",
    daysInStatus: 38,
    adjustedNet: 890,
    gateClassification: "marginal",
    lastOutreachAction: "Call completed",
    lastOutreachDate: "Mar 27",
    nextAction: "DCA review",
    nextActionOverdue: false,
    nextActionDueToday: false,
    autoFlagged: false,
    tenureMonths: 20,
    dcaName: "Laura White",
    teamLeadName: "Mark Anderson",
    teamLeadPhone: "(206) 555-0190",
    gate2Exempt: false,
    newHireExempt: false,
    dcaReviewOutcome: "pending",
    rentalStartDate: "2025-02-21",
    outreachStatus: "no_contact",
  },
  {
    id: "s5t6u7v8",
    name: "Lisa Washington",
    ldap: "lwashi05",
    market: "Philadelphia",
    currentStatus: "exempt_scorecard",
    daysInStatus: 0,
    adjustedNet: 7200,
    gateClassification: "profitable",
    lastOutreachAction: "N/A",
    lastOutreachDate: "—",
    nextAction: "None — Exempt",
    nextActionOverdue: false,
    nextActionDueToday: false,
    autoFlagged: false,
    tenureMonths: 44,
    dcaName: "Greg Harris",
    teamLeadName: "Betty Clark",
    teamLeadPhone: "(215) 555-0133",
    gate2Exempt: true,
    newHireExempt: false,
    dcaReviewOutcome: "cleared",
    rentalStartDate: "2023-07-10",
    outreachStatus: "completed",
  },
];

export const dashboardStats = {
  totalTechsInScope: 74,
  inExceptionWindow: 23,
  activeEscalations: 6,
  overdueCheckIns: 11,
  monthlyCostAvoided: 41808,
};
