// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/nexus-dashboard/ActionFirst.tsx": () => import("../components/mockups/nexus-dashboard/ActionFirst.tsx"),
  "./components/mockups/nexus-dashboard/CommandCenter.tsx": () => import("../components/mockups/nexus-dashboard/CommandCenter.tsx"),
  "./components/mockups/nexus-dashboard/MinimalGrid.tsx": () => import("../components/mockups/nexus-dashboard/MinimalGrid.tsx"),
  "./components/mockups/nexus-dashboard/OperationsHub.tsx": () => import("../components/mockups/nexus-dashboard/OperationsHub.tsx"),
  "./components/mockups/nexus-dashboard/StatusBoard.tsx": () => import("../components/mockups/nexus-dashboard/StatusBoard.tsx"),
  "./components/mockups/nexus-integration/FleetScopeLanding.tsx": () => import("../components/mockups/nexus-integration/FleetScopeLanding.tsx"),
  "./components/mockups/nexus-integration/LandingPage.tsx": () => import("../components/mockups/nexus-integration/LandingPage.tsx"),
  "./components/mockups/nexus-integration/SidebarMenu.tsx": () => import("../components/mockups/nexus-integration/SidebarMenu.tsx")
};
